Repository nuxt/framework, pull requests merged in 2022-05, with the labels that each got.

#4645 fix(nuxt): process middleware after plugins
  packages/nuxt/src/app/plugins/router.ts
  packages/nuxt/src/pages/runtime/router.ts
  test/fixtures/basic/middleware/redirect.global.ts
  test/fixtures/basic/plugins/my-plugin.ts
Labels: bug, app, 🔨 p3-minor-bug

#4304 feat(nitro): add `nitro:build:before` hook
  packages/nuxt/src/core/nitro.ts
  packages/schema/src/types/hooks.ts
  packages/vite/src/server.ts
Labels: bug, pending, nitro, ❗ p4-important

#4841 fix(nuxt): normalise window location for universal router
  packages/nuxt/src/app/plugins/router.ts
  packages/nuxt/src/pages/runtime/router.ts
Labels: bug, 🔨 p3-minor-bug

#4824 docs(data-fetching): fix and improve example
  docs/content/2.guide/2.features/5.data-fetching.md
Labels: documentation

#4837 feat(nuxt)!: upgrade `nitropack` to `0.4.x`
  packages/nuxt/package.json
  packages/nuxt/src/core/nitro.ts
  yarn.lock
Labels: enhancement

#4849 fix(schema): add back `PublicRuntimeConfig` interface for augmentation
  packages/nuxt/src/core/templates.ts
  packages/schema/src/types/config.ts
Labels: types, schema

#4915 fix(nuxt): configure vite to transpile nuxt
  packages/nuxt/src/core/nitro.ts
  packages/vite/src/server.ts
Labels: bug, 🔨 p3-minor-bug

#4933 fix(nuxt): respect baseurl when redirecting (and universal router)
  packages/nuxt/src/app/composables/router.ts
  packages/nuxt/src/app/plugins/router.ts
  test/basic.test.ts
  test/fixtures/basic/pages/navigate-to.vue
Labels: bug, 🔨 p3-minor-bug

#4913 fix(nuxt): check for 404s after user middleware
  packages/nuxt/src/pages/runtime/router.ts
Labels: bug, pages, 🔨 p3-minor-bug

#4958 feat(vite): replace `global` with `globalThis`
  packages/vite/package.json
  packages/vite/src/vite.ts
  yarn.lock
Labels: enhancement, vite

#4912 fix(nuxi): only reload for top level dirs
  packages/nuxi/src/commands/dev.ts
Labels: bug, cli, 🍰 p2-nice-to-have

#4995 docs: add missing parentheses in the `alias` example
  packages/schema/src/config/_common.ts
Labels: documentation

#4990 docs: fix typo in environment variable
  packages/schema/src/config/_common.ts
Labels: documentation

#4974 docs(data-fetching): add note about difference between `useFetch` and `useAsyncData`
  docs/content/2.guide/2.features/5.data-fetching.md
Labels: documentation

#4985 docs(api): improve `useFetch` docs for body type and additional ohmyfetch options
  docs/content/3.api/1.composables/use-fetch.md
Labels: documentation

#5044 docs(middleware): add `navigateTo` options
  docs/content/2.guide/3.directory-structure/7.middleware.md
Labels: documentation

#5059 docs: demonstrate the multiple `useState` with same key
  examples/composables/use-state/app.vue
Labels: documentation

#4982 fix(nuxt): fix router redirection on aliased page
  packages/nuxt/src/pages/runtime/router.ts
Labels: bug, pages, 🔨 p3-minor-bug

#5071 fix(nuxt): allow passing extraneous attrs to meta components
  packages/nuxt/src/head/runtime/components.ts
Labels: bug, 🔨 p3-minor-bug

#5064 fix(nuxt): add default empty title to trigger `titleTemplate`
  packages/nuxt/src/head/runtime/plugin.ts
Labels: bug, 🔨 p3-minor-bug

#5145 fix(nuxt): respect `navigateTo` options using server middleware in server-side
  packages/nuxt/src/app/composables/router.ts
Labels: bug, 🔨 p3-minor-bug

#5190 refactor(vite, webpack, test-utils): use caret range for `vue` peer dependency
  packages/test-utils/package.json
  packages/vite/package.json
  packages/webpack/package.json
  yarn.lock
Labels: chore, 🧹 p1-chore
