Repository nuxt/framework, pull requests merged in 2022-08, with the labels that each got.

#6257 fix(nuxt): do not allow catchalls to have child routes
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/pages.test.ts
Labels: bug, pages, 🔨 p3-minor-bug

#6279 fix(nuxt): narrow `nuxt.config` import protection
  packages/nuxt/src/core/plugins/import-protection.ts
Labels: bug, 🔨 p3-minor-bug

#6275 fix(nuxt): separate routes for different suspense forks
  packages/nuxt/src/app/components/nuxt-root.vue
  packages/nuxt/src/app/composables/router.ts
  packages/nuxt/src/pages/runtime/page.ts
  packages/nuxt/src/pages/runtime/router.ts
Labels: bug, pages

#6165 feat(nuxt): remove wrapper from client only components
  packages/nuxt/src/app/components/client-only.mjs
  test/basic.test.ts
  test/fixtures/basic/components/ClientWrapped.client.vue
  test/fixtures/basic/pages/index.vue
Labels: bug, 🔨 p3-minor-bug

#6306 feat(nuxt): add `setResponseStatus`
  docs/content/3.api/1.composables/set-response-status.md
  packages/nuxt/src/app/composables/index.ts
  packages/nuxt/src/app/composables/ssr.ts
  packages/nuxt/src/auto-imports/presets.ts
Labels: enhancement, 🍰 p2-nice-to-have

#6325 fix(nuxt): extract component to provide route
  packages/nuxt/src/pages/runtime/page.ts
Labels: bug, pages, ❗ p4-important

#6331 fix(nuxt): remove literal `<script setup>` from comment
  packages/nuxt/src/app/components/client-only.mjs
Labels: upstream

#6352 fix(nuxt): better equality check for json cookies
  packages/nuxt/src/app/composables/cookie.ts
Labels: bug, 🔨 p3-minor-bug

#6349 fix(nuxt): make route provided to page children reactive
  packages/nuxt/src/pages/runtime/page.ts
Labels: bug, pages, 🔨 p3-minor-bug

#6350 fix(nuxt): resolve plugins and middleware to their full path
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/plugins/unctx.ts
  test/fixtures/basic/modules/example.ts
  test/fixtures/basic/modules/runtime/middleware.ts
  test/fixtures/basic/modules/runtime/plugin.ts
Labels: bug, 🔨 p3-minor-bug

#6355 fix(vite): use url for entry on windows
  packages/vite/src/dev-bundler.ts
  packages/vite/src/manifest.ts
  packages/vite/src/vite-node.ts
  packages/vite/src/vite.ts
Labels: bug, vite, windows, ❗ p4-important

#6372 test: add key matching test for keyed composables
  test/basic.test.ts
  test/fixtures/basic/pages/keyed-composables.vue
Labels: test

#6376 fix(nuxt): remove side-effect imports from page metadata
  packages/nuxt/src/pages/macros.ts
  test/basic.test.ts
Labels: bug, 🔨 p3-minor-bug

#6395 fix(nuxt): type `useRoute` return
  packages/nuxt/src/app/composables/router.ts
Labels: bug, types

#6210 feat(nuxt): update to `vue-bundle-renderer@0.4`
  packages/nuxt/package.json
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/vite/package.json
  packages/vite/src/manifest.ts
  packages/vite/src/vite-node.ts
  packages/webpack/package.json
  packages/webpack/src/plugins/vue/client.ts
  yarn.lock
Labels: enhancement

#6378 fix(schema): cleanup meta tags and deduplicate charset/viewport
  packages/nuxt/src/head/module.ts
  packages/schema/src/config/_app.ts
  test/basic.test.ts
  test/fixtures/basic/nuxt.config.ts
Labels: bug, dx, schema, 🍰 p2-nice-to-have

#6415 fix(nuxt): revert unplugin upgrade
  packages/nuxt/package.json
  packages/vite/package.json
  packages/webpack/package.json
  yarn.lock
Labels: bug

#6430 fix(kit): move relative path handling back into nuxt templates
  packages/kit/package.json
  packages/kit/src/internal/template.ts
  packages/nuxt/src/core/templates.ts
  yarn.lock
Labels: bug, kit

#6389 fix(nuxt): use payload error state as source of truth
  packages/nuxt/src/app/composables/error.ts
  packages/nuxt/src/app/entry.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/runtime/nitro/error.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: bug, 🔨 p3-minor-bug

#6446 chore: update lockfile
  yarn.lock
Labels: chore

#6448 fix(vite): add `module` type to vite node entry
  packages/vite/src/vite-node.ts
Labels: bug

#6441 fix(nuxt): handle immediate errors when calling `useAsyncData`
  packages/nuxt/src/app/composables/asyncData.ts
Labels: bug

#6382 fix(nuxt): ensure component dirs in `node_modules` have lower scanning priority
  packages/nuxt/src/components/module.ts
Labels: bug

#6468 fix(nuxt): interopDefault for page component imports
  packages/nuxt/src/pages/utils.ts
  packages/schema/src/config/experimental.ts
Labels: bug

#6472 fix(nuxt): ensure asyncdata handler has nuxt app context
  packages/nuxt/src/app/composables/asyncData.ts
Labels: bug, ❗ p4-important

#6487 refactor(nuxt)!: remove `null` handling for `titleTemplate`
  packages/nuxt/src/head/runtime/lib/vueuse-head.plugin.ts
  test/fixtures/basic/pages/index.vue
Labels: bug, 🍰 p2-nice-to-have

#6488 fix(nuxt): log fatal errors as well as unhandled ones
  packages/nuxt/src/core/runtime/nitro/error.ts
Labels: bug, nitro

#6514 fix(nuxi): fix issues with `nuxi upgrade`
  packages/nuxi/src/commands/upgrade.ts
  packages/nuxi/src/utils/fs.ts
Labels: bug, cli, ❗ p4-important

#6520 build: use `npm@8.10.0` to publish packages
  scripts/release-edge.sh
  scripts/release-rc.sh
Labels: ❗ p4-important

#6529 fix(vite): remove `/@fs` from external ids
  packages/vite/src/dev-bundler.ts
Labels: ❗ p4-important

#6546 fix(vite, nuxt): resolve relative to `srcDir` rather than `rootDir`
  packages/nuxt/src/components/module.ts
  packages/vite/src/client.ts
  packages/vite/src/plugins/cache-dir.ts
  packages/vite/src/plugins/dev-ssr-css.ts
  packages/vite/src/runtime/vite-node.mjs
  packages/vite/src/vite-node.ts
Labels: bug, vite

#6505 feat(webpack, vite): default to `.js` extension for client
  packages/schema/src/config/webpack.ts
  packages/vite/src/client.ts
Labels: bug, vite, webpack, 🍰 p2-nice-to-have

#6580 fix(nuxt): remove stray commas in component templates
  packages/nuxt/src/components/templates.ts
Labels: types, 🔨 p3-minor-bug

#6595 fix(nuxi): update `server.port` and `server.host` with listener info
  packages/nuxi/src/commands/dev.ts
  packages/vite/src/vite-node.ts
Labels: bug, vite, 🔨 p3-minor-bug

#6490 docs: global style imports
  docs/content/2.guide/2.features/3.assets.md
Labels: documentation

#6637 fix(vite): pass relative url as default base
  packages/vite/src/client.ts
Labels: bug, vite, 🔨 p3-minor-bug

#6640 fix(nuxt): don't set asyncData to existing payload on CSR if `initialCache` is disabled
  packages/nuxt/src/app/composables/asyncData.ts
Labels: bug, 🔨 p3-minor-bug

#6507 docs(server): add nitro config and storage examples
  docs/content/2.guide/2.features/9.server-routes.md
Labels: documentation

#6662 feat(nuxt): exclude page chunks from being prefetched
  packages/nuxt/src/pages/module.ts
  packages/schema/build.config.ts
  packages/schema/src/types/hooks.ts
  packages/vite/src/manifest.ts
  packages/webpack/src/plugins/vue/client.ts
  packages/webpack/src/presets/vue.ts
Labels: enhancement, pages, 🍰 p2-nice-to-have

#6709 test: update type assertion tests to strict equality
  test/fixtures/basic/types.ts
Labels: chore, test

#6713 fix(nuxt): use `vue-devtools-stub` to mock `@vue/devtools-api` for both cjs + esm
  packages/nuxt/package.json
  packages/nuxt/src/core/nitro.ts
  test/fixtures/basic/pages/index.vue
  yarn.lock
Labels: bug, nitro

#6735 fix(vite): dedupe `vue` in client bundle
  packages/vite/src/client.ts
Labels: enhancement, vite

#6740 docs: make wording slightly clearer
  docs/content/2.guide/3.directory-structure/7.layouts.md
Labels: documentation

#6741 docs: fix typo in `defineEventHandler` example
  docs/content/2.guide/2.features/9.server-routes.md
Labels: documentation

#6745 docs(api): add `<NuxtWelcome />` component docs
  docs/content/3.api/2.components/6-nuxt-welcome.md
Labels: documentation

#6789 fix(nuxt): ensure component helper methods do not create side-effects
  packages/nuxt/src/components/loader.ts
Labels: bug, 🔨 p3-minor-bug

#6857 fix(nuxt): throw hard error on initial spa load if aborted
  packages/nuxt/src/pages/runtime/router.ts
Labels: bug, 🔨 p3-minor-bug

#5469 feat(nuxt): add warning in dev mode if layouts/pages do not have a single root node
  packages/nuxt/src/app/components/layout.ts
  packages/nuxt/src/pages/runtime/page.ts
  test/basic.test.ts
  test/fixtures/basic/layouts/invalid-root.vue
  test/fixtures/basic/pages/invalid-root/1.vue
  test/fixtures/basic/pages/invalid-root/2.vue
  test/fixtures/basic/pages/invalid-root/3.vue
  test/fixtures/basic/pages/invalid-root/4.vue
  test/fixtures/basic/pages/invalid-root/fine.vue
Labels: dx, 🍰 p2-nice-to-have

#6868 feat!(schema): enable external vue by default
  packages/schema/src/config/experimental.ts
Labels: enhancement

#6871 fix(nuxt): pass analyze options through to nitro
  packages/nuxt/src/core/nitro.ts
Labels: bug

#5859 feat(nuxt): config options for default keepalive, page & layout transitions
  docs/content/2.guide/3.directory-structure/10.pages.md
  packages/nuxt/src/app/components/layout.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/head/module.ts
  packages/nuxt/src/head/runtime/plugin.ts
  packages/nuxt/src/pages/runtime/page.ts
  packages/schema/src/config/_app.ts
  packages/schema/src/types/config.ts
Labels: enhancement, 🍰 p2-nice-to-have

#6661 feat(nuxt): allow programmatically prefetching global components
  docs/content/3.api/1.composables/prefetch-components.md
  docs/content/3.api/1.composables/preload-components.md
  packages/nuxt/src/app/composables/index.ts
  packages/nuxt/src/app/composables/preload.ts
  packages/nuxt/src/components/templates.ts
  packages/nuxt/src/imports/presets.ts
  test/basic.test.ts
  test/fixtures/basic/pages/prefetch/components.vue
Labels: enhancement, components, 🍰 p2-nice-to-have

#3921 feat(nuxi): support mode flags for `add` command
  docs/content/3.api/5.commands/add.md
  packages/nuxi/src/commands/add.ts
  packages/nuxi/src/utils/templates.ts
Labels: enhancement, cli

#6901 fix(nuxt): lazy composables shouldn't block setup in `ssr: false`
  packages/nuxt/src/app/composables/asyncData.ts
Labels: bug, 🔨 p3-minor-bug

#6826 feat(nuxt): add `setLayout` utility
  docs/content/3.api/1.composables/set-layout.md
  examples/routing/layouts/middleware/other.ts
  examples/routing/layouts/pages/index.vue
  examples/routing/layouts/pages/other.vue
  packages/nuxt/src/app/composables/index.ts
  packages/nuxt/src/app/composables/router.ts
  packages/nuxt/src/app/plugins/router.ts
  packages/nuxt/src/imports/presets.ts
  packages/nuxt/src/pages/runtime/router.ts
  test/basic.test.ts
  test/fixtures/basic/middleware/sets-layout.ts
  test/fixtures/basic/pages/with-dynamic-layout.vue
Labels: pending

#7015 docs: replace backtick with apostrophe
  docs/content/bridge/2.bridge-composition-api.md
Labels: documentation

#7021 fix(vite): remove client manifest.json from public dir
  packages/vite/src/manifest.ts
Labels: bug, 🔨 p3-minor-bug

#6999 docs(schema): update prefix for runtime config env variables
  packages/schema/src/config/_common.ts
Labels: documentation

#7019 docs: add information on how to use options api asyncData
  docs/content/2.guide/2.features/5.data-fetching.md
  test/basic.test.ts
  test/fixtures/basic/pages/legacy/async-data.vue
Labels: documentation, test

#7067 fix(vite): sanitize client asset chunk names
  packages/vite/src/client.ts
Labels: bug, vite, 🔨 p3-minor-bug

#7069 perf(nuxt): don't prefetch all global components
  packages/nuxt/src/components/module.ts
  test/basic.test.ts
Labels: bug, 🍰 p2-nice-to-have, performance

#7102 docs: increment directory structure numbers
  docs/content/2.guide/3.directory-structure/19.package.md
  docs/content/2.guide/3.directory-structure/20.tsconfig.md
Labels: documentation

#7119 fix(nuxt): prevent error page rendering a null error
  packages/nuxt/src/app/components/nuxt-error-page.vue
Labels: bug, 🔨 p3-minor-bug
