Repository nuxt/framework, pull requests merged in 2022-06, with the labels that each got.

#5273 docs: small typo in the "catch-all route" description
  docs/content/2.guide/2.features/9.server-routes.md
Labels: documentation

#5272 fix(nuxt): support `RouterView` props in `NuxtPage`
  packages/nuxt/src/pages/runtime/page.ts
Labels: bug, 🍰 p2-nice-to-have

#5270 docs(pages): add information for typing page metadata
  docs/content/2.guide/3.directory-structure/10.pages.md
Labels: documentation

#5333 fix(nuxt): add `ssrContext` types on `NuxtApp`
  packages/nuxt/src/app/composables/ssr.ts
  packages/nuxt/src/app/entry.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: bug, types

#5355 fix(nuxt): relax server import protections
  packages/nuxt/src/core/plugins/import-protection.ts
Labels: bug, 🍰 p2-nice-to-have

#5345 docs: add warning against layout as root element
  docs/content/2.guide/3.directory-structure/6.layouts.md
Labels: documentation

#4904 feat(nuxt): support auto imports within `<template>`
  packages/nuxt/src/auto-imports/module.ts
  packages/nuxt/src/auto-imports/transform.ts
  test/basic.test.ts
  test/fixtures/basic/composables/template.ts
  test/fixtures/basic/pages/index.vue
Labels: enhancement

#5366 docs: update keepalive key name
  docs/content/migration/6.pages-and-layouts.md
Labels: documentation

#5326 docs: add `useRequestEvent`
  docs/content/3.api/1.composables/use-request-event.md
Labels: documentation

#4983 fix(nuxt): sort routes with dynamic params at the end
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/pages.test.ts
Labels: bug, pages, 🔨 p3-minor-bug

#5300 fix(nuxt): keep route param optionality when sibling is an index
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/pages.test.ts
Labels: bug, pages, 🔨 p3-minor-bug

#4949 docs(api): add docs for `useRouter` composable
  docs/content/3.api/1.composables/use-router.md
Labels: documentation

#5375 fix(kit): pass resolved path to `isIgnored`
  packages/kit/src/resolve.ts
Labels: bug, 🔨 p3-minor-bug

#4906 fix(vite, kit, nuxt): generate safe variable names using knitwork
  packages/kit/package.json
  packages/kit/src/internal/template.ts
  packages/nuxt/package.json
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/utils.ts
  packages/vite/package.json
  yarn.lock
Labels: bug, 🔨 p3-minor-bug

#5394 revert(nuxt): revert router hotfix #4983
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/pages.test.ts
Labels: 🧹 p1-chore

#5043 fix(webpack): respect `build.transpile`
  packages/webpack/src/presets/base.ts
Labels: bug, webpack, ❗ p4-important

#5042 fix(nuxt): transform extends layers within `node_modules`
  packages/nuxt/src/auto-imports/module.ts
  packages/nuxt/src/auto-imports/transform.ts
  packages/nuxt/src/core/nuxt.ts
  test/fixtures/basic/.gitignore
  test/fixtures/basic/extends/foo/server/middleware/foo.ts
  test/fixtures/basic/extends/node_modules/foo/app/router.options.ts
  test/fixtures/basic/extends/node_modules/foo/components/ExtendsFoo.vue
  test/fixtures/basic/extends/node_modules/foo/components/ExtendsOverride.vue
  test/fixtures/basic/extends/node_modules/foo/composables/foo.ts
  test/fixtures/basic/extends/node_modules/foo/layouts/default.vue
  test/fixtures/basic/extends/node_modules/foo/layouts/override.vue
  test/fixtures/basic/extends/node_modules/foo/middleware/foo.ts
  test/fixtures/basic/extends/node_modules/foo/middleware/override.ts
  test/fixtures/basic/extends/node_modules/foo/nuxt.config.ts
  test/fixtures/basic/extends/node_modules/foo/pages/foo.vue
  test/fixtures/basic/extends/node_modules/foo/pages/override.vue
  test/fixtures/basic/extends/node_modules/foo/plugins/foo.ts
  test/fixtures/basic/extends/node_modules/foo/server/api/foo.ts
  test/fixtures/basic/extends/node_modules/foo/server/middleware/foo.ts
  test/fixtures/basic/nuxt.config.ts
Labels: enhancement, 🍰 p2-nice-to-have

#5323 fix(nuxt): throw an error when using unknown route middleware
  docs/content/2.guide/3.directory-structure/6.layouts.md
  docs/content/2.guide/3.directory-structure/7.middleware.md
  packages/nuxt/src/pages/runtime/router.ts
Labels: bug, dx, 🍰 p2-nice-to-have

#5409 fix(vite): don't terminate with escaped delimiters
  packages/vite/src/plugins/dynamic-base.ts
  test/basic.test.ts
  test/fixtures/basic/pages/assets.vue
Labels: bug, vite, ❗ p4-important

#5421 fix(nuxt): exclude non-cwd auto-imports and don't process _all_ files
  packages/nuxt/src/auto-imports/transform.ts
  packages/nuxt/src/core/nuxt.ts
Labels: bug, 🔥 p5-urgent, edge

#5428 fix(nuxt): ignore whitespace and commas within `resolveComponent`
  docs/content/2.guide/3.directory-structure/4.components.md
  packages/nuxt/src/components/loader.ts
Labels: bug, 🔨 p3-minor-bug

#5417 fix(nuxi): always override `NODE_ENV`
  packages/nuxi/src/commands/analyze.ts
  packages/nuxi/src/commands/build.ts
  packages/nuxi/src/commands/dev.ts
  packages/nuxi/src/utils/env.ts
Labels: bug, cli, 🍰 p2-nice-to-have

#4388 fix(webpack): set `extractCSS: true` by default
  packages/schema/src/config/webpack.ts
  packages/webpack/build.config.ts
  packages/webpack/package.json
  packages/webpack/src/presets/style.ts
  yarn.lock
Labels: bug, pending, webpack, ❗ p4-important

#5462 docs: rewrite note wording
  docs/content/2.guide/1.concepts/2.vuejs-development.md
Labels: documentation

#5472 fix(schema): add types for `vite:` hooks
  packages/schema/package.json
  packages/schema/src/types/hooks.ts
  yarn.lock
Labels: bug, schema

#5461 fix(nuxt): normalize string transpile paths for windows
  packages/nuxt/src/core/nuxt.ts
Labels: bug, 🔨 p3-minor-bug

#5464 fix(vite): add typecheck to _vite_ plugins
  packages/vite/src/server.ts
Labels: bug, vite, ❗ p4-important

#5560 feat(kit): support client and server flags for `addVitePlugin`
  packages/kit/src/build.ts
Labels: enhancement, kit

#5569 docs: update usage about runtime config and environment variables
  docs/content/migration/8.runtime-config.md
Labels: documentation

#5537 feat(kit): add `addLayout`
  packages/kit/src/index.ts
  packages/kit/src/layout.ts
  packages/kit/src/module/container.ts
Labels: enhancement, kit

#5118 docs(layouts): rework the layout section, add default layout
  docs/content/2.guide/3.directory-structure/6.layouts.md
Labels: documentation

#5038 feat(nuxt)!: support universal global middleware
  examples/routing/universal-router/middleware/always-run.global.ts
  packages/nuxt/src/app/plugins/router.ts
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/plugins/unctx.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/core/utils.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/utils.ts
  packages/schema/src/types/hooks.ts
  packages/schema/src/types/nuxt.ts
Labels: enhancement, 🍰 p2-nice-to-have

#5668 fix(nuxt): pass attrs and props to client-only components
  packages/nuxt/src/app/components/client-only.mjs
Labels: bug, 🔨 p3-minor-bug
