Repository nuxt/framework, pull requests merged in 2022-11, with the labels that each got.

#8544 fix(nuxt): add `vue-router` to optimized deps
  packages/nuxt/src/pages/module.ts
Labels: bug, 🔨 p3-minor-bug

#8601 fix(vite): handle all vite middleware routes
  packages/vite/src/client.ts
Labels: 🔨 p3-minor-bug

#8529 fix(nuxt): check before appending comma in composable keys
  packages/vite/src/plugins/composable-keys.ts
Labels: bug, 🔨 p3-minor-bug

#8536 fix(nuxt)!: use parser to generate page metadata
  packages/nuxt/package.json
  packages/nuxt/src/pages/macros.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/page-meta.ts
  packages/nuxt/src/pages/utils.ts
  packages/vite/src/plugins/composable-keys.ts
  pnpm-lock.yaml
  test/basic.test.ts
  test/fixtures/basic/pages/index.vue
Labels: bug, ❗ p4-important, performance

#8626 fix(kit): normalize nitro handler paths
  packages/kit/src/nitro.ts
Labels: bug, vite, kit

#8633 feat(nuxt): allow setting `name` and `path` for a route in `definePageMeta`
  docs/content/2.guide/2.directory-structure/1.pages.md
  packages/nuxt/src/pages/runtime/composables.ts
  packages/nuxt/src/pages/utils.ts
Labels: enhancement

#8639 fix(nuxt): don't force prerender `/` if user doesn't have that route
  packages/nuxt/src/pages/module.ts
Labels: bug

#8635 feat(kit): add `addServerPlugin` utility
  packages/kit/src/nitro.ts
Labels: enhancement, kit

#8666 fix(nuxt): do not inline global styles in HTML response
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/vite/src/plugins/ssr-styles.ts
  packages/vite/src/server.ts
  test/basic.test.ts
Labels: bug, 🔨 p3-minor-bug

#8667 fix(schema)!: use strict typescript mode by default
  packages/schema/src/config/typescript.ts
Labels: types, 🍰 p2-nice-to-have

#8669 test: update type test for strict mode
  test/fixtures/basic/components/Nested/SugarCounter.vue
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/client-only-components.vue
  test/fixtures/basic/pages/useAsyncData/refresh.vue
  test/fixtures/basic/types.ts
Labels: test

#8769 fix(nuxt): allow cookies to be set to `null` to unset them
  packages/nuxt/src/app/composables/cookie.ts
  test/fixtures/basic/types.ts
Labels: bug, types, 🔨 p3-minor-bug

#8782 fix(nuxt): add catchall paths to prerender list
  packages/nuxt/src/pages/module.ts
Labels: bug

#8809 refactor(nuxt)!: remove support for `404.vue` shorthand
  packages/nuxt/src/pages/runtime/router.ts
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/pages.test.ts
Labels: bug, 🍰 p2-nice-to-have, breaking-change

#8819 chore(nuxt): remove unused plugins
  packages/nuxt/src/app/plugins/logs.client.dev.ts
  packages/nuxt/src/app/plugins/progress.client.ts
Labels: chore

#8821 fix(nuxt): do not render page if we are throwing error
  packages/nuxt/src/pages/runtime/router.ts
Labels: bug

#8822 style(nuxt): lint `Route` interface
  packages/nuxt/src/app/plugins/router.ts
Labels: chore, 🧹 p1-chore

#8843 fix(nuxt): swallow issues with query selectors
  packages/nuxt/src/pages/runtime/router.options.ts
Labels: bug, 🔨 p3-minor-bug

#8729 refactor(nuxt): explicitly import app in nuxt-root
  packages/nuxt/src/app/components/nuxt-root.vue
  packages/nuxt/src/app/entry.ts
Labels: performance

#8817 feat(nuxt): auto-import `utils/` directory
  docs/content/2.guide/2.directory-structure/1.composables.md
  docs/content/2.guide/2.directory-structure/1.utils.md
  packages/nuxi/src/commands/dev.ts
  packages/nuxt/src/imports/module.ts
  packages/schema/src/types/imports.ts
  test/fixtures/basic/utils/useBar.ts
Labels: enhancement

#8852 fix(nuxt)!: only add `$f` fetch prefix to auto-keys
  packages/nuxt/src/app/composables/fetch.ts
  test/basic.test.ts
Labels: bug

#8860 docs: add entry for `extendPages`
  docs/content/3.api/4.advanced/2.kit.md
Labels: documentation

#8848 fix(nuxi): exclude `dist` from type checking
  packages/nuxi/src/utils/prepare.ts
Labels: bug, cli

#8815 fix(test-utils)!: use `vitest/node` subpath export
  packages/test-utils/src/run.ts
Labels: bug, test-utils

#8861 docs: get event before running async function
  docs/content/1.getting-started/6.data-fetching.md
Labels: documentation

#8881 fix(nuxt): detect non-functional imports within page meta
  packages/nuxt/src/pages/page-meta.ts
  test/fixtures/basic/pages/index.vue
  test/fixtures/basic/some-exports.ts
Labels: bug, 🔨 p3-minor-bug

#8889 feat(nuxt): add `onBeforeRouteLeave` and `onBeforeRouteUpdate` composables
  packages/nuxt/src/app/composables/index.ts
  packages/nuxt/src/app/composables/router.ts
  packages/nuxt/src/imports/module.ts
  packages/nuxt/src/imports/presets.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/test/auto-imports.test.ts
Labels: enhancement, 🍰 p2-nice-to-have

#8895 docs: add stub documentation for router composables
  docs/content/3.api/1.composables/on-before-route-leave.md
  docs/content/3.api/1.composables/on-before-route-update.md
Labels: documentation

#8967 docs(api): add spaces to avoid breaking mobile layout
  docs/content/3.api/5.commands/add.md
Labels: documentation

#8921 fix(nuxt): avoid passing attrs to default slot for ClientOnly
  packages/nuxt/src/app/components/client-only.mjs
Labels: bug, 🔨 p3-minor-bug

#9006 fix(vite): add extend layers to `fs.allow`
  packages/vite/src/vite.ts
Labels: bug

#9010 refactor(kit)!: remove support for module container
  docs/content/7.migration/20.module-authors.md
  packages/kit/src/index.ts
  packages/kit/src/module/container.ts
  packages/kit/src/module/install.ts
  packages/schema/src/types/module.ts
Labels: enhancement, kit

#9014 fix(nuxt): include layers in esbuild transform
  packages/nuxt/src/core/nitro.ts
Labels: bug

#8901 refactor(nuxt)!: move `head` option support into `defineNuxtComponent`
  docs/content/3.api/3.utils/define-nuxt-component.md
  packages/nuxt/src/app/composables/component.ts
  packages/nuxt/src/app/index.ts
  packages/nuxt/src/head/module.ts
  packages/nuxt/src/head/runtime/composables.ts
  packages/nuxt/src/head/runtime/mixin-plugin.ts
  packages/nuxt/src/imports/presets.ts
  test/basic.test.ts
  test/bundle.test.ts
  test/fixtures/basic/pages/head.vue
Labels: bug, performance

#6632 fix(nuxt)!: include request url and params in `useFetch` key
  packages/nuxt/src/app/composables/fetch.ts
Labels: bug, pending, 🔨 p3-minor-bug

#9050 fix(schema): initialise `runtimeConfig.public` with empty object
  packages/schema/src/config/common.ts
Labels: bug, schema

#9059 docs: add missing agencies
  docs/content/4.support/2.agencies/91.funkhaus.md
  docs/content/4.support/2.agencies/92.the-coding-machine.md
  docs/content/4.support/2.agencies/93.epicmax.md
  docs/public/assets/support/agencies/full/dark/epicmax.svg
  docs/public/assets/support/agencies/full/dark/funkhaus.svg
  docs/public/assets/support/agencies/full/dark/the-coding-machine.svg
  docs/public/assets/support/agencies/full/light/epicmax.svg
  docs/public/assets/support/agencies/full/light/funkhaus.svg
  docs/public/assets/support/agencies/full/light/the-coding-machine.svg
  docs/public/assets/support/agencies/square/dark/epicmax.svg
  docs/public/assets/support/agencies/square/dark/funkhaus.svg
  docs/public/assets/support/agencies/square/dark/the-coding-machine.svg
  docs/public/assets/support/agencies/square/light/epicmax.svg
  docs/public/assets/support/agencies/square/light/funkhaus.svg
  docs/public/assets/support/agencies/square/light/the-coding-machine.svg
Labels: documentation

#9114 chore: update example nuxt versions
  examples/advanced/config-extends/package.json
  examples/advanced/jsx/package.json
  examples/advanced/module-extend-pages/package.json
  examples/advanced/testing/package.json
  examples/app-config/package.json
  examples/app/error-handling/package.json
  examples/app/plugins/package.json
  examples/app/teleport/package.json
  examples/auto-imports/components/package.json
  examples/auto-imports/composables/package.json
  examples/composables/use-async-data/package.json
  examples/composables/use-cookie/package.json
  examples/composables/use-fetch/package.json
  examples/composables/use-head/package.json
  examples/composables/use-state/package.json
  examples/essentials/hello-world/package.json
  examples/experimental/reactivity-transform/package.json
  examples/experimental/vite-node/package.json
  examples/experimental/wasm/package.json
  examples/other/locale/package.json
  examples/routing/layouts/package.json
  examples/routing/middleware/package.json
  examples/routing/nuxt-link/package.json
  examples/routing/pages/package.json
  examples/routing/universal-router/package.json
  examples/server/routes/package.json
Labels: chore

#9276 docs: add missing space
  docs/content/1.docs/1.getting-started/6.data-fetching.md
Labels: documentation

#9263 docs: add warning about `.client` onMounted hook
  docs/content/1.docs/2.guide/2.directory-structure/1.components.md
Labels: documentation

#5689 feat(nuxt): server component islands
  packages/nuxt/src/app/components/island-renderer.ts
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/components/nuxt-root.vue
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/scan.ts
  packages/nuxt/src/components/templates.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/nuxt/test/fixture/components/global/Glob.vue
  packages/nuxt/test/fixture/components/islands/Isle.vue
  packages/nuxt/test/fixture/components/some-glob.global.vue
  packages/nuxt/test/fixture/components/some.island.vue
  packages/nuxt/test/scan-components.test.ts
  packages/schema/src/config/experimental.ts
  packages/schema/src/types/components.ts
  test/basic.test.ts
  test/fixtures/basic/components/islands/PureComponent.vue
  test/fixtures/basic/components/islands/RouteComponent.vue
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/islands.vue
  test/fixtures/basic/plugins/my-plugin.ts
Labels: enhancement, 🍰 p2-nice-to-have

#9395 fix(nuxt): allow layouts to receive custom props
  packages/nuxt/src/app/components/layout.ts
  test/basic.test.ts
  test/fixtures/basic/layouts/with-props.vue
  test/fixtures/basic/pages/layouts/with-props.vue
Labels: bug, 🔨 p3-minor-bug
