Repository nuxt/framework, pull requests merged in 2022-07, with the labels that each got.

#5721 fix(webpack): transpile `vue-demi`
  packages/webpack/src/presets/base.ts
Labels: bug, webpack

#5739 docs(api): update commands with new `NODE_ENV` behavior
  docs/content/3.api/5.commands/analyze.md
  docs/content/3.api/5.commands/build.md
  docs/content/3.api/5.commands/dev.md
Labels: documentation

#5748 fix(nuxt): `useRequestHeaders` type should allow for undefined values
  packages/nuxt/src/app/composables/ssr.ts
Labels: bug, types, 🍰 p2-nice-to-have

#5710 fix(nuxt): update `useFetch` key warning to include any function or blob
  packages/nuxt/src/app/composables/fetch.ts
Labels: dx, 🍰 p2-nice-to-have

#5630 perf(nuxt)!: remove legacy app context
  packages/nuxt/src/app/compat/legacy-app.ts
  packages/nuxt/src/app/composables/component.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/components/templates.ts
  packages/schema/src/config/experimental.ts
Labels: enhancement, 🍰 p2-nice-to-have

#5767 fix: pin vue-router to 4.0 minor branch
  packages/nuxt/package.json
  renovate.json
  yarn.lock
Labels: bug, upstream

#5709 feat(nuxt): prerender all pages by default
  packages/nuxt/src/pages/module.ts
Labels: enhancement, pages, 🍰 p2-nice-to-have

#4955 feat(nuxt): automatically generate unique keys for keyed composables
  .eslintrc
  docs/content/3.api/1.composables/use-async-data.md
  docs/content/3.api/1.composables/use-fetch.md
  docs/content/3.api/1.composables/use-state.md
  examples/composables/use-async-data/components/CounterExample.vue
  package.json
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/fetch.ts
  packages/nuxt/src/app/composables/state.ts
  packages/vite/package.json
  packages/vite/src/plugins/composable-keys.ts
  packages/vite/src/utils/index.ts
  packages/vite/src/vite.ts
  packages/webpack/package.json
  packages/webpack/src/webpack.ts
  test/basic.test.ts
  test/fixtures/basic/pages/keyed-composables.vue
  test/fixtures/basic/types.ts
  yarn.lock
Labels: enhancement, dx, 🍰 p2-nice-to-have

#5786 fix(nuxt): don't return stub function from tree-shaken composables
  packages/nuxt/src/core/plugins/tree-shake.ts
Labels: bug

#5817 fix(test-utils): upate vitest import path with `.mjs`
  packages/test-utils/src/run.ts
Labels: bug, test-utils

#5850 fix(nuxt): only tree-shake composables on their own lines
  packages/nuxt/src/core/plugins/tree-shake.ts
Labels: bug

#5847 refactor(nuxt): add import protection to nitro config
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/plugins/import-protection.ts
Labels: nitro

#5857 fix(nuxt): warn about legacy and invalid plugins
  packages/nuxt/src/app/nuxt.ts
Labels: bug

#5875 fix(vite): close vite watcher before building
  packages/vite/src/vite.ts
Labels: bug, vite

#5881 docs: fixed a typo
  docs/content/2.guide/6.going-further/7.testing.md
Labels: documentation

#5785 docs: improve runtimeConfig example
  docs/content/2.guide/2.features/10.runtime-config.md
Labels: documentation

#5879 docs: add way to pass `.env` variables to nuxt app in production
  docs/content/2.guide/2.features/10.runtime-config.md
Labels: documentation

#5750 perf(nuxt): tree-shake client-only components from ssr bundle
  docs/content/2.guide/3.directory-structure/4.components.md
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/tree-shake.ts
  test/fixtures/basic/pages/client.vue
Labels: enhancement, 🍰 p2-nice-to-have

#5929 fix(kit): only call `viteExtendConfig` callback once if possible
  packages/kit/src/build.ts
Labels: kit

#5930 fix(nuxt): lazy load and tree-shake error templates
  packages/nuxt/src/app/components/nuxt-error-page.vue
  packages/nuxt/src/app/components/nuxt-root.vue
Labels: 🔨 p3-minor-bug

#5987 fix(webpack): do not resolve `#internal/nitro` alias internally
  packages/vite/src/plugins/dynamic-base.ts
Labels: bug, webpack

#6010 fix(nuxt)!: change `statusCode` type to number for error page template
  packages/nuxt/src/app/components/nuxt-error-page.vue
Labels: bug, dx, 🍰 p2-nice-to-have

#6003 docs: Add warning about non-serializable datatypes in useState
  docs/content/2.guide/2.features/6.state-management.md
Labels: documentation

#5994 docs: warn that `useState` should only contain JSON-serializable content
  docs/content/2.guide/2.features/6.state-management.md
  docs/content/3.api/1.composables/use-state.md
Labels: documentation

#5916 docs(runtime-config): clarify how environment variables are loaded
  docs/content/2.guide/2.features/10.runtime-config.md
Labels: documentation

#5398 feat(vite)!: upgrade vite to v3
  package.json
  packages/nuxt/src/components/loader.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/pages/macros.ts
  packages/schema/package.json
  packages/schema/src/config/vite.ts
  packages/vite/package.json
  packages/vite/src/client.ts
  packages/vite/src/dev-bundler.ts
  packages/vite/src/manifest.ts
  packages/vite/src/plugins/dynamic-base.ts
  packages/vite/src/server.ts
  packages/vite/src/vite.ts
  packages/webpack/src/plugins/dynamic-base.ts
  packages/webpack/src/presets/base.ts
  packages/webpack/src/webpack.ts
  vitest.config.ts
  yarn.lock
Labels: enhancement, vite

#6033 fix(pages): ignore expression delimiters within quotes
  packages/nuxt/src/pages/macros.ts
  test/fixtures/basic/pages/no-auth.vue
Labels: bug, pages, ❗ p4-important

#6035 fix(nuxt): always write nitro types when building
  packages/nuxt/src/core/nitro.ts
Labels: bug, nitro, 🔨 p3-minor-bug

#6037 fix(kit): resolve aliases in plugin src
  packages/kit/src/plugin.ts
Labels: bug, kit, 🔨 p3-minor-bug

#6038 fix(vite): invalidate virtual files when changed
  packages/vite/src/vite.ts
Labels: bug, dx, vite, ❗ p4-important

#4539 feat(nuxt): improve error dx for users
  docs/content/2.guide/2.features/7.error-handling.md
  docs/content/3.api/3.utils/create-error.md
  docs/content/3.api/3.utils/show-error.md
  docs/content/3.api/3.utils/throw-error.md
  examples/app/error-handling/app.vue
  examples/app/error-handling/middleware/error.global.ts
  packages/nuxt/src/app/components/nuxt-root.vue
  packages/nuxt/src/app/composables/error.ts
  packages/nuxt/src/app/composables/index.ts
  packages/nuxt/src/app/plugins/router.ts
  packages/nuxt/src/auto-imports/presets.ts
  packages/nuxt/src/core/runtime/nitro/error.ts
  packages/nuxt/src/pages/runtime/router.ts
Labels: enhancement, 🔨 p3-minor-bug

#6063 fix(vite): ignore baseurl when pruning manifest
  packages/vite/src/client.ts
  packages/vite/src/manifest.ts
  packages/vite/src/server.ts
  test/basic.test.ts
Labels: bug, vite, 🔨 p3-minor-bug

#6116 fix(nuxt): don't ignore components dirs with same prefix
  packages/nuxt/src/components/scan.ts
Labels: bug, 🔨 p3-minor-bug

#6119 fix(nuxi): load `.env` file before starting dev server
  packages/nuxi/src/commands/dev.ts
  packages/nuxi/src/commands/preview.ts
Labels: bug, cli, 🍰 p2-nice-to-have

#6112 fix(nuxt): normalize manifest css file entries
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  test/basic.test.ts
Labels: webpack

#6082 fix(vite): allow overriding client hmr options
  packages/vite/src/client.ts
  packages/vite/src/server.ts
Labels: bug, vite, 🔨 p3-minor-bug

#4825 refactor(nuxt): enhance `useFetch` and `useLazyFetch` request type
  docs/content/2.guide/2.features/5.data-fetching.md
  docs/content/3.api/1.composables/use-fetch.md
  packages/nuxt/src/app/composables/fetch.ts
  packages/nuxt/src/core/runtime/nitro/error.ts
  test/fixtures/basic/types.ts
Labels: enhancement, dx, 🍰 p2-nice-to-have

#6128 build(vite): add missing `pkg-types` dependency
  packages/vite/package.json
  yarn.lock
Labels: bug, ❗ p4-important

#6155 fix(schema): add empty noscript array
  packages/schema/src/config/_app.ts
Labels: schema

#6042 feat(nuxt): `app:rendered` and `app:response` hooks
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/nuxt/src/core/templates.ts
Labels: enhancement

#6174 fix(nuxt): allow `useHead` to accept computed values
  packages/nuxt/src/head/runtime/composables.ts
Labels: types, 🔨 p3-minor-bug

#6176 fix(schema): exclude functions from `DeepPartial`
  packages/schema/src/config/_app.ts
  packages/schema/src/types/config.ts
Labels: types, 🔨 p3-minor-bug

#6070 feat(nuxt): add support for `components/global`
  docs/content/2.guide/3.directory-structure/4.components.md
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/scan.ts
  packages/nuxt/src/components/templates.ts
  packages/schema/src/config/_adhoc.ts
  test/basic.test.ts
  test/fixtures/basic/components/WithSuffix.global.vue
  test/fixtures/basic/components/global/TestGlobal.vue
  test/fixtures/basic/pages/index.vue
Labels: enhancement, 🍰 p2-nice-to-have

#6201 fix(nuxt): don't call renderMeta if it is not defined
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: bug, 🔨 p3-minor-bug

#6191 fix(vite, webpack): generate composable keys based on order
  packages/vite/src/plugins/composable-keys.ts
Labels: bug, ❗ p4-important

#6192 test: wrap components with `<div>`
  test/fixtures/basic/components/WithSuffix.global.vue
  test/fixtures/basic/components/global/TestGlobal.vue
Labels: test

#6220 fix(schema): add typings for `vite.vue` options
  packages/schema/build.config.ts
  packages/schema/src/config/vite.ts
  packages/schema/src/types/config.ts
Labels: bug, types, schema

#6215 fix(vite): fix distDir resolution
  packages/vite/src/client.ts
  packages/vite/src/dirs.ts
Labels: bug, ❗ p4-important

#6232 fix(webpack): output `.mjs` to use crossorigin preloads
  packages/schema/src/config/webpack.ts
  test/utils.ts
Labels: bug, webpack, ❗ p4-important

#6233 fix(kit): try extensions with `resolvePath` with absolute input
  packages/kit/src/resolve.ts
Labels: bug
