Repository nuxt/framework, pull requests merged in 2022-04, with the labels that each got.

#4016 feat(nuxi): load `.env` when previewing builds
  docs/content/3.docs/1.usage/8.cli.md
  packages/nuxi/package.json
  packages/nuxi/src/commands/preview.ts
  yarn.lock
Labels: enhancement, cli, 🍰 p2-nice-to-have

#4022 fix(bridge): remove `defineNuxtLink` from auto-imports
  packages/bridge/src/auto-imports.ts
Labels: bug, bridge, 🍰 p2-nice-to-have

#4023 docs: add `router.extendRoutes` example to migration docs
  docs/content/3.docs/3.migration/2.configuration.md
Labels: documentation

#4005 refactor(bridge): align bridge with vite and inline systemjs polyfill in entry
  packages/bridge/src/vite/client.ts
  packages/bridge/src/vite/manifest.ts
  packages/bridge/src/vite/module.ts
  packages/bridge/src/vite/server.ts
  packages/bridge/src/vite/vite.ts
  packages/vite/src/client.ts
  packages/vite/src/plugins/dynamic-base.ts
  packages/vite/src/server.ts
  packages/vite/src/vite.ts
  packages/webpack/src/webpack.ts
  test/bridge.test.ts
  test/fixtures/bridge/assets/logo.svg
  test/fixtures/bridge/pages/assets.vue
  test/fixtures/bridge/static/public.svg
Labels: bug, bridge, ❗ p4-important

#3909 feat(nitro): support for rendering ssr teleports to body
  .eslintrc
  docs/content/3.docs/1.usage/10.teleports.md
  docs/content/4.examples/1.app/teleport.md
  examples/app/teleport/app.vue
  examples/app/teleport/components/MyModal.vue
  examples/app/teleport/nuxt.config.ts
  examples/app/teleport/package.json
  examples/app/teleport/tsconfig.json
  packages/nitro/src/runtime/app/render.ts
  packages/nuxt3/src/core/templates.ts
  yarn.lock
Labels: enhancement, nitro, 🍰 p2-nice-to-have

#3914 docs: update data fetching for `$fetch` and refresh
  docs/content/3.docs/1.usage/1.data-fetching.md
Labels: documentation

#3776 fix(kit): add typings to kit server middleware
  packages/kit/build.config.ts
  packages/kit/src/server.ts
Labels: enhancement

#4058 fix(nuxt3): use inferred type for `useFetch`
  packages/nuxt3/src/app/composables/asyncData.ts
  packages/nuxt3/src/app/composables/fetch.ts
Labels: bug, nuxt3, types

#4070 fix(bridge): transpile `@nuxt/bridge-edge`
  packages/bridge/src/transpile.ts
  packages/nuxt3/src/core/modules.ts
Labels: bug, bridge, 🔨 p3-minor-bug

#4067 fix(nuxt3): set pending to false when using cached data
  packages/nuxt3/src/app/composables/asyncData.ts
Labels: bug, nuxt3, 🔨 p3-minor-bug

#4083 docs: update `useBody` comment to reflect usable methods
  docs/content/3.docs/2.directory-structure/13.server.md
Labels: documentation

#4068 docs: document `nuxi analyze` command
  docs/content/3.docs/1.usage/8.cli.md
Labels: documentation

#3923 docs(community): add documentation contribution guide
  docs/content/5.community/3.contribution.md
Labels: documentation

#4092 fix(nuxt3)!: sync route object to currently resolved page
  packages/nuxt3/src/pages/runtime/router.ts
Labels: bug, nuxt3, pages, 🍰 p2-nice-to-have

#4121 fix(nuxt3): parse macro queries for components
  packages/nuxt3/src/components/loader.ts
Labels: bug, nuxt3, components, 🔨 p3-minor-bug

#4124 fix(nuxt3): move new router behavior to `useActiveRoute`
  packages/bridge/src/auto-imports.ts
  packages/nuxt3/src/app/composables/index.ts
  packages/nuxt3/src/app/composables/router.ts
  packages/nuxt3/src/auto-imports/presets.ts
  packages/nuxt3/src/pages/runtime/router.ts
Labels: bug, nuxt3, pages, ❗ p4-important

#4130 fix(vite): clean up dynamic paths
  packages/vite/src/plugins/dynamic-base.ts
  packages/vite/src/server.ts
Labels: enhancement, vite, 🍰 p2-nice-to-have

#4133 fix(nuxt3): normalize watched paths
  packages/nuxt3/src/core/builder.ts
Labels: bug, nuxt3, ❗ p4-important

#4147 docs(bridge): fix bridge composition api link
  docs/static/_redirects
  packages/bridge/src/runtime/capi.legacy.mjs
Labels: documentation, bridge

#4146 fix(bridge): resolve vue from `.nuxt`, not `node_modules`
  packages/bridge/src/app.ts
Labels: bug, bridge, ❗ p4-important

#4153 docs: remove `yarn dlx` instruction
  docs/content/1.getting-started/1.quick-start.md
Labels: documentation

#4151 docs: add note that layout root cannot be `<slot />`
  docs/content/2.guide/3.directory-structure/6.layouts.md
Labels: documentation

#4150 feat(nuxt3): allow explicitly importing components
  docs/content/2.guide/3.directory-structure/4.components.md
  packages/nuxt3/src/components/module.ts
  packages/nuxt3/src/components/templates.ts
Labels: enhancement, nuxt3, components, 🍰 p2-nice-to-have

#4127 fix(bridge): exclude unsupported imports via `autoImports:sources`
  packages/bridge/src/auto-imports.ts
Labels: bug, bridge, 🔨 p3-minor-bug

#4019 fix(nuxt3)!: add default cookie path to `/`
  packages/nuxt3/src/app/composables/cookie.ts
Labels: bug, enhancement, pending, nuxt3, 🍰 p2-nice-to-have

#4072 docs(migration): add programmatic navigation example to pages and layouts
  docs/content/migration/6.pages-and-layouts.md
Labels: documentation

#4074 docs: add programmatic navigation
  docs/content/2.guide/3.directory-structure/10.pages.md
Labels: documentation

#3778 fix(webpack): add `exportOnlyLocals: true` for css modules options in server build.
  packages/webpack/src/presets/style.ts
Labels: bug, webpack, 🔨 p3-minor-bug

#4159 docs(api): specify nuxt-error-boundary events and slots
  docs/content/3.api/2.components/5.nuxt-error-boundary.md
Labels: documentation

#4164 docs(api): specify abortNavigation API
  docs/content/3.api/3.utils/abort-navigation.md
Labels: documentation

#4165 docs: update runtime config migration
  docs/content/migration/8.runtime-config.md
Labels: documentation

#4170 fix(bridge): inline bridge dist files
  packages/bridge/src/nitro.ts
Labels: bug, bridge, 🔥 p5-urgent

#4169 fix(nuxt3): export useRequestEvent from `#app`
  packages/nuxt3/src/app/composables/index.ts
Labels: bug, ❗ p4-important

#4172 fix(bridge): add missing dependency
  packages/bridge/package.json
  yarn.lock
Labels: bug, bridge

#3755 chore(ci): enable testing fixtures in development
  .github/workflows/ci.yml
  package.json
  packages/test-utils/src/nuxt.ts
  packages/test-utils/src/server.ts
  test/basic.test.ts
  test/bridge.test.ts
  vitest.config.ts
Labels: test, 🧹 p1-chore

#4195 fix(bridge): add ui-templates dependency
  packages/bridge/package.json
  yarn.lock
Labels: bug, bridge, ❗ p4-important

#4193 docs: update deployment urls & azure instructions
  docs/content/2.guide/5.deployment/1.azure.md
  docs/content/2.guide/5.deployment/2.cloudflare.md
  docs/content/2.guide/5.deployment/3.firebase.md
  docs/content/2.guide/5.deployment/4.netlify.md
Labels: documentation

#4202 docs: move specific alert components to atoms directory
  docs/components/atoms/NeedContribution.vue
  docs/components/atoms/ReadMore.vue
Labels: documentation

#4216 fix(nuxt3): remove useMeta warning
  packages/nuxt3/src/head/runtime/composables.ts
Labels: bug, dx

#4215 fix(nuxt3,bridge): rename error handler url
  packages/bridge/src/nitro.ts
  packages/nuxt3/src/core/nitro.ts
  packages/nuxt3/src/core/runtime/nitro/error.ts
  packages/nuxt3/src/core/runtime/nitro/renderer.ts
Labels: bug, ❗ p4-important

#4174 docs: add server routes documentation
  docs/content/2.guide/2.features/9.api-routes.md
  docs/content/2.guide/2.features/9.server-routes.md
  docs/content/2.guide/3.directory-structure/13.server.md
Labels: documentation

#4218 fix(bridge)!: move `@vueuse/head` to dev dependencies
  packages/bridge/package.json
  packages/bridge/src/meta.ts
Labels: bug, bridge

#4260 fix(nuxt3): re-enable computed metadata in useHead
  packages/nuxt3/src/head/runtime/lib/vueuse-head.plugin.ts
Labels: bug, nuxt3, 🔨 p3-minor-bug

#4148 docs: improve documentation
  docs/content/2.guide/2.features/13.modules.md
  docs/content/3.api/1.composables/use-head.md
  docs/content/3.api/3.utils/clear-error.md
  docs/content/3.api/3.utils/throw-error.md
Labels: documentation

#4284 docs: complete features/modules section
  docs/content/2.guide/2.features/13.modules.md
Labels: documentation

#4286 chore: update links for new sitemap
  packages/bridge/README.md
  packages/nuxi/README.md
  packages/schema/src/config/_adhoc.ts
Labels: documentation

#3968 fix(vite-node): on-demand manifest generation
  examples/experimental/vite-node/app.vue
  examples/experimental/vite-node/nuxt.config.ts
  examples/experimental/vite-node/package.json
  examples/experimental/vite-node/tsconfig.json
  packages/vite/src/runtime/client.manifest.mjs
  packages/vite/src/runtime/server.mjs
  packages/vite/src/runtime/vite-node-shared.d.ts
  packages/vite/src/runtime/vite-node-shared.mjs
  packages/vite/src/runtime/vite-node.mjs
  packages/vite/src/vite-node.ts
  yarn.lock
Labels: enhancement, vite

#4308 refactor(nuxi): remove `rimraf` dependency
  packages/nuxi/package.json
  packages/nuxi/src/utils/fs.ts
  yarn.lock
Labels: enhancement

#4289 fix(nuxt3): render nuxt custom error page
  packages/bridge/package.json
  packages/bridge/src/nitro.ts
  packages/nuxt3/package.json
  packages/nuxt3/src/core/nitro.ts
  packages/nuxt3/src/core/runtime/nitro/error.ts
  test/basic.test.ts
  test/bridge.test.ts
  yarn.lock
Labels: bug, nitro, nuxt3, ❗ p4-important

#4320 fix(deps): upgrade @vueuse/head
  packages/bridge/package.json
  packages/nuxt3/package.json
  yarn.lock
Labels: bug, 🔨 p3-minor-bug

#4332 docs(api): apply use-async-data page structure to use-fetch
  docs/content/3.api/1.composables/use-fetch.md
Labels: documentation

#4327 feat(nuxt3): allow manually enabling/disabling the ad-hoc pages module
  packages/nuxt3/src/pages/module.ts
  packages/schema/src/config/_adhoc.ts
Labels: enhancement, nuxt3, 🍰 p2-nice-to-have

#4301 docs: add server-routes example
  docs/content/4.examples/5.server/routes.md
  docs/content/4.examples/6.advanced/config-extends.md
  docs/content/4.examples/6.advanced/module-extend-pages.md
  docs/content/4.examples/6.advanced/testing.md
  docs/content/4.examples/7.experimental/reactivity-transform.md
  docs/content/4.examples/7.experimental/wasm.md
  docs/content/4.examples/8.other/locale.md
  examples/server/routes/app.vue
  examples/server/routes/nuxt.config.ts
  examples/server/routes/package.json
  examples/server/routes/server/api/mountain.js
  examples/server/routes/tsconfig.json
  yarn.lock
Labels: documentation

#4326 feat(nuxt3): allow providing a ref as default value
  docs/content/3.api/1.composables/use-async-data.md
  docs/content/3.api/1.composables/use-cookie.md
  docs/content/3.api/1.composables/use-state.md
  packages/nuxt3/src/app/composables/asyncData.ts
  packages/nuxt3/src/app/composables/cookie.ts
  packages/nuxt3/src/app/composables/state.ts
  packages/nuxt3/src/app/composables/utils.ts
  test/fixtures/basic/types.ts
Labels: enhancement, nuxt3, 🍰 p2-nice-to-have

#4346 fix(nuxi): call listen on each nuxt restart
  packages/nuxi/src/commands/dev.ts
Labels: bug, cli, 🍰 p2-nice-to-have

#4333 docs(api): document lazy wrappers for data fetching
  docs/content/3.api/1.composables/use-lazy-async-data.md
  docs/content/3.api/1.composables/use-lazy-fetch.md
Labels: documentation

#4361 test(nuxt3): add test case for computed head
  test/fixtures/basic/pages/head.vue
Labels: nuxt3, test

#4355 docs: update webpack code examples
  packages/schema/src/config/webpack.ts
Labels: documentation

#4360 fix(nuxt3): directly emit `document.template.mjs`
  packages/nuxt3/src/core/nitro.ts
  packages/nuxt3/src/core/templates.ts
Labels: bug, nuxt3, 🔨 p3-minor-bug

#4375 fix(webpack): add css, sass, scss to asset patterns to transpile
  packages/webpack/src/configs/server.ts
Labels: bug, webpack, ❗ p4-important

#4378 build(vite): don't inline `h3`
  packages/vite/package.json
  yarn.lock
Labels: chore

#4384 chore: use `node:` prefix for built-in modules
  .eslintrc
  docs/content/2.guide/3.directory-structure/4.components.md
  docs/content/2.guide/5.deployment/99.presets/custom.md
  docs/content/2.guide/5.deployment/99.presets/node.md
  docs/content/2.guide/6.going-further/5.esm.md
  docs/nuxt.config.ts
  docs/scripts/gen-docs.ts
  examples/advanced/testing/tests/basic.test.ts
  packages/kit/src/ignore.ts
  packages/kit/src/internal/cjs.ts
  packages/kit/src/internal/template.ts
  packages/kit/src/module/define.ts
  packages/kit/src/resolve.ts
  packages/kit/src/template.ts
  packages/nuxi/src/commands/add.ts
  packages/nuxi/src/commands/analyze.ts
  packages/nuxi/src/commands/info.ts
  packages/nuxi/src/commands/init.ts
  packages/nuxi/src/commands/preview.ts
  packages/nuxi/src/commands/upgrade.ts
  packages/nuxi/src/utils/cjs.ts
  packages/nuxi/src/utils/fs.ts
  packages/nuxi/src/utils/packageManagers.ts
  packages/nuxi/src/utils/prepare.ts
  packages/nuxt3/src/app/compat/legacy-app.ts
  packages/nuxt3/src/auto-imports/composables.ts
  packages/nuxt3/src/auto-imports/transform.ts
  packages/nuxt3/src/components/loader.ts
  packages/nuxt3/src/components/module.ts
  packages/nuxt3/src/core/app.ts
  packages/nuxt3/src/core/nitro.ts
  packages/nuxt3/src/core/plugins/import-protection.ts
  packages/nuxt3/src/dirs.ts
  packages/nuxt3/src/pages/macros.ts
  packages/nuxt3/src/pages/module.ts
  packages/nuxt3/test/auto-imports.test.ts
  packages/nuxt3/test/scan-components.test.ts
  packages/schema/src/config/_app.ts
  packages/schema/src/config/_common.ts
  packages/schema/src/types/hooks.ts
  packages/test-utils/src/context.ts
  packages/test-utils/src/nuxt.ts
  packages/test-utils/src/server.ts
  packages/vite/src/dev-bundler.ts
  packages/vite/src/dirs.ts
  packages/vite/src/utils/index.ts
  packages/webpack/src/configs/client.ts
  packages/webpack/src/webpack.ts
  scripts/bump-edge.ts
  scripts/update-examples.ts
  test/basic.test.ts
  test/fixtures/basic/extends/foo/server/middleware/foo.ts
  vitest.config.ts
Labels: chore, 🧹 p1-chore

#4379 feat(vite,webpack): build/dev typechecking
  docs/content/2.guide/1.concepts/6.typescript.md
  docs/content/3.api/5.commands/typecheck.md
  packages/schema/src/config/typescript.ts
  packages/vite/package.json
  packages/vite/src/server.ts
  packages/webpack/package.json
  packages/webpack/src/configs/server.ts
  yarn.lock
Labels: enhancement, vite, webpack, 🍰 p2-nice-to-have

#4422 fix(nuxt3)!: include route children in parent suspense
  packages/nuxt3/src/pages/runtime/page.ts
Labels: bug, pages, 🔨 p3-minor-bug

#4427 fix(nuxt3): initialise router with normalised url
  packages/nuxt3/src/pages/runtime/router.ts
Labels: bug, pages, 🔨 p3-minor-bug

#4381 docs: remove `__dirname` and `__filename` from example code
  docs/content/2.guide/3.directory-structure/4.components.md
  docs/content/2.guide/5.deployment/99.presets/custom.md
  docs/content/2.guide/6.going-further/5.esm.md
  docs/content/2.guide/6.going-further/7.testing.md
  packages/schema/src/config/_common.ts
  packages/schema/src/config/router.ts
  packages/schema/src/config/server.ts
Labels: documentation

#4431 fix(schema): use entire object for `app` properties
  packages/schema/src/config/_common.ts
  packages/schema/src/config/build.ts
  packages/schema/src/config/generate.ts
  packages/schema/src/config/router.ts
Labels: bug, ❗ p4-important

#4430 fix(nuxt3): improve redirect lifecycle
  packages/nuxt3/src/app/composables/cookie.ts
  packages/nuxt3/src/app/composables/router.ts
  packages/nuxt3/src/app/nuxt.ts
  packages/nuxt3/src/app/plugins/router.ts
  packages/nuxt3/src/pages/runtime/router.ts
Labels: bug, nuxt3, 🔨 p3-minor-bug

#4390 feat(nuxt3): allow separating client and server components
  examples/auto-imports/components/app.vue
  examples/auto-imports/components/components/ClientAndServer.client.vue
  examples/auto-imports/components/components/ClientAndServer.server.vue
  examples/auto-imports/components/components/JustClient.client.vue
  packages/kit/src/components.ts
  packages/nuxt3/src/app/components/client-only.mjs
  packages/nuxt3/src/app/components/server-placeholder.ts
  packages/nuxt3/src/components/loader.ts
  packages/nuxt3/src/components/module.ts
  packages/nuxt3/src/components/scan.ts
  packages/nuxt3/src/components/templates.ts
  packages/nuxt3/src/core/nuxt.ts
  packages/nuxt3/test/fixture/components/Nuxt3.client.vue
  packages/nuxt3/test/fixture/components/Nuxt3.server.vue
  packages/nuxt3/test/fixture/components/parent-folder/index.server.vue
  packages/nuxt3/test/scan-components.test.ts
  packages/schema/src/types/components.ts
Labels: enhancement, nuxt3, 🍰 p2-nice-to-have

#4300 fix(nuxi): strip extensions from absolute paths (for types)
  packages/nuxi/src/utils/prepare.ts
Labels: bug, cli, 🔨 p3-minor-bug

#4454 fix(nuxt3): don't rely on auto-imports for `defineAsyncComponent`
  packages/nuxt/src/components/loader.ts
Labels: bug, components, ❗ p4-important

#4451 docs: update nitro runtime port + host var names
  docs/content/2.guide/5.deployment/2.node-server.md
Labels: documentation, nitro

#4456 fix(nuxt3): default client-side fetch to use baseURL
  packages/nuxt/src/app/entry.ts
Labels: bug, nuxt3, 🔨 p3-minor-bug

#4461 docs: add note about runtime config fallback
  docs/content/2.guide/2.features/10.runtime-config.md
Labels: documentation

#4477 fix(nuxt3): respect custom public dir in layers
  packages/nuxt/src/core/nitro.ts
Labels: bug, 🍰 p2-nice-to-have

#4512 fix(vite): transform virtual templates
  packages/vite/src/plugins/virtual.ts
Labels: bug, vite, 🔨 p3-minor-bug

#4453 chore: setup IssueUp
  .github/issue-up.yml
Labels: pending, 🧹 p1-chore

#4509 feat: allow disabling sourcemap generation
  packages/nuxt/src/auto-imports/module.ts
  packages/nuxt/src/auto-imports/transform.ts
  packages/nuxt/src/components/loader.ts
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/unctx.ts
  packages/nuxt/src/pages/macros.ts
  packages/nuxt/src/pages/module.ts
  packages/schema/src/config/build.ts
  packages/vite/src/plugins/dynamic-base.ts
  packages/vite/src/vite.ts
  packages/webpack/src/webpack.ts
Labels: enhancement, pending, 🍰 p2-nice-to-have

#4577 chore(docs): update social card
  docs/nuxt.config.ts
Labels: documentation

#4549 docs(api): fix `useAsyncData` example
  docs/content/3.api/1.composables/use-async-data.md
Labels: documentation

#4593 docs: add layout to match custom header example
  docs/content/2.guide/3.directory-structure/6.layouts.md
Labels: documentation

#4596 fix(vite): don't match across newlines
  packages/vite/src/plugins/dynamic-base.ts
Labels: bug, vite, 🔨 p3-minor-bug

#4595 fix(nuxi): don't strip file extensions from dirs in `tsconfig`
  packages/nuxi/src/utils/prepare.ts
Labels: bug, cli, 🔨 p3-minor-bug

#4537 feat(pages)!: explicitly allow optional params with `[[`
  docs/content/2.guide/3.directory-structure/10.pages.md
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/pages.test.ts
Labels: enhancement, pages

#4590 fix(nuxt): warn to provide a key for `useFetch` with `transform` option
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/fetch.ts
Labels: bug, 🔨 p3-minor-bug

#4563 docs(features): complete assets page
  docs/content/2.guide/2.features/3.assets.md
Labels: documentation

#4679 docs: fix typos
  docs/content/2.guide/1.concepts/2.vuejs-development.md
  docs/content/2.guide/5.deploy/providers/netlify.md
  docs/content/2.guide/6.going-further/5.esm.md
  docs/content/5.community/3.contribution.md
  docs/content/migration/20.module-authors.md
Labels: documentation

#4677 fix(nuxt): use suspense for child pages on client-side navigation
  packages/nuxt/src/pages/runtime/page.ts
Labels: bug, ❗ p4-important

#4714 docs: add note that `.env` is not read in production
  docs/content/2.guide/2.features/10.runtime-config.md
Labels: documentation

#4666 fix(nuxt): mark config head as non-reactive
  packages/nuxt/src/head/module.ts
  packages/nuxt/src/head/runtime/plugin.ts
Labels: bug, nuxt3, 🔨 p3-minor-bug
