Repository nuxt/framework, pull requests merged in 2022-12, with the labels that each got.

#9449 fix(nuxt): `useCookie` with defaults should return non-null value
  packages/nuxt/src/app/composables/cookie.ts
  test/fixtures/basic/types.ts
Labels: bug, types

#9475 fix(nuxt): defer render-blocking prefetches until after load
  packages/nuxt/src/app/components/nuxt-link.ts
  packages/nuxt/src/app/nuxt.ts
  packages/vite/src/client.ts
Labels: bug

#9472 fix(nuxt): update head entry when speculation rules are updated
  packages/nuxt/src/app/plugins/cross-origin-prefetch.client.ts
Labels: bug, 🔨 p3-minor-bug

#9543 docs: recommend to install non-dge version of `@nuxt/test-utils`
  docs/content/1.docs/1.getting-started/11.testing.md
  docs/content/1.docs/2.guide/3.going-further/3.modules.md
Labels: documentation

#9599 fix(kit): support applying `.nuxtignore` within external layers
  packages/kit/src/ignore.ts
Labels: bug, kit

#9636 fix(nuxt): remove deprecated `req`/`res` access
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: bug, 🍰 p2-nice-to-have

#9152 docs: update examples link
  README.md
Labels: documentation

#9607 docs: add docs for `preloadRouteComponents`
  docs/content/1.docs/3.api/3.utils/preload-route-components.md
Labels: documentation

#9602 fix(vite): skip _only_ vite transform middleware
  packages/vite/src/client.ts
Labels: bug, vite

#9655 fix(nuxt): remove absolute paths from routes objects
  packages/nuxt/src/pages/utils.ts
Labels: bug, 🍰 p2-nice-to-have

#9679 fix(nuxt): make dev-only regexp less greedy
  packages/nuxt/src/core/plugins/dev-only.ts
  test/fixtures/basic/pages/index.vue
Labels: bug, 🔨 p3-minor-bug

#9630 refactor(nuxt): do not add all composable auto-imports to `globalThis`
  packages/nuxt/src/imports/module.ts
Labels: bug, chore, 🍰 p2-nice-to-have

#9706 docs: add docs landing page
  docs/content/1.docs/0.index.md
  docs/content/1.docs/1.getting-started/1.introduction.md
  docs/package.json
  docs/public/assets/docs/getting-started/views/docs-landing/advanced-dark.svg
  docs/public/assets/docs/getting-started/views/docs-landing/advanced-light.svg
  docs/public/assets/docs/getting-started/views/docs-landing/commands-dark.svg
  docs/public/assets/docs/getting-started/views/docs-landing/commands-light.svg
  docs/public/assets/docs/getting-started/views/docs-landing/community-dark.svg
  docs/public/assets/docs/getting-started/views/docs-landing/community-light.svg
  docs/public/assets/docs/getting-started/views/docs-landing/components-dark.svg
  docs/public/assets/docs/getting-started/views/docs-landing/components-light.svg
  docs/public/assets/docs/getting-started/views/docs-landing/composables-dark.svg
  docs/public/assets/docs/getting-started/views/docs-landing/composables-light.svg
  docs/public/assets/docs/getting-started/views/docs-landing/configuration-dark.svg
  docs/public/assets/docs/getting-started/views/docs-landing/configuration-light.svg
  docs/public/assets/docs/getting-started/views/docs-landing/directory-structure-dark.svg
  docs/public/assets/docs/getting-started/views/docs-landing/directory-structure-light.svg
  docs/public/assets/docs/getting-started/views/docs-landing/examples-dark.svg
  docs/public/assets/docs/getting-started/views/docs-landing/examples-light.svg
  docs/public/assets/docs/getting-started/views/docs-landing/going-further-dark.svg
  docs/public/assets/docs/getting-started/views/docs-landing/going-further-light.svg
  docs/public/assets/docs/getting-started/views/docs-landing/key-concepts-dark.svg
  docs/public/assets/docs/getting-started/views/docs-landing/key-concepts-light.svg
  docs/public/assets/docs/getting-started/views/docs-landing/utils-dark.svg
  docs/public/assets/docs/getting-started/views/docs-landing/utils-light.svg
  docs/public/assets/docs/getting-started/views/getting-started-dark.png
  docs/public/assets/docs/getting-started/views/getting-started-light.png
  docs/public/assets/docs/getting-started/views/hero-nuxt-docs-dark.png
  docs/public/assets/docs/getting-started/views/hero-nuxt-docs-light.png
  docs/yarn.lock
Labels: documentation
