Repository nuxt/framework, pull requests merged in 2022-10, with the labels that each got.

#7946 fix(nuxt): handle schema types for relative module paths
  packages/nuxt/src/core/templates.ts
Labels: bug, 🔨 p3-minor-bug

#7931 chore: clean up some root workspace dependencies
  package.json
  packages/schema/package.json
  yarn.lock
Labels: chore, 🧹 p1-chore

#7930 fix(vite): add type-checker to client build for `ssr: false`
  packages/vite/src/server.ts
  packages/vite/src/vite.ts
Labels: bug

#7925 ci(crawl): ignore `<a>` links without hrefs
  scripts/crawl.mjs
Labels: bug, chore

#7866 fix(test-utils): respect `setupTimeout`
  packages/test-utils/src/context.ts
  packages/test-utils/src/setup/jest.ts
  packages/test-utils/src/setup/vitest.ts
Labels: bug, 🔨 p3-minor-bug, test-utils

#7865 chore: downgrade node v16 minor
  package.json
  packages/kit/package.json
  packages/nuxi/package.json
  packages/nuxt/package.json
  packages/schema/package.json
  packages/test-utils/package.json
  packages/vite/package.json
  packages/webpack/package.json
Labels: chore, 🍰 p2-nice-to-have

#7831 fix(nuxt): don't prerender index.html with a server
  packages/nuxt/src/core/nitro.ts
Labels: bug, 🔨 p3-minor-bug

#7981 feat(nuxt): allow configuring plugins directory
  packages/nuxt/src/core/app.ts
  packages/schema/src/config/_common.ts
Labels: enhancement, 🍰 p2-nice-to-have

#8045 docs: fix more redirect issues
  docs/content/1.getting-started/2.installation.md
  docs/content/1.getting-started/4.assets.md
  docs/content/1.getting-started/5.seo-meta.md
  docs/content/1.getting-started/6.data-fetching.md
  docs/content/2.guide/1.concepts/1.auto-imports.md
  docs/content/2.guide/1.concepts/3.rendering.md
  docs/content/2.guide/1.concepts/5.modules.md
  docs/content/2.guide/1.concepts/8.typescript.md
  docs/content/2.guide/2.directory-structure/1.pages.md
  docs/content/3.api/1.composables/use-fetch.md
  docs/content/3.api/1.composables/use-head.md
  docs/content/3.api/3.utils/add-route-middleware.md
  docs/content/3.api/3.utils/define-nuxt-route-middleware.md
  docs/content/3.api/3.utils/define-page-meta.md
  docs/content/3.api/3.utils/prefetch-components.md
  docs/content/3.api/5.commands/typecheck.md
  docs/content/4.examples/3.composables/use-head.md
  docs/content/5.community/4.framework-contribution.md
  docs/content/6.bridge/1.overview.md
  docs/content/6.bridge/2.bridge-composition-api.md
  docs/content/7.migration/1.overview.md
  docs/content/7.migration/4.meta.md
  docs/public/_redirects
  scripts/crawl.mjs
Labels: documentation

#8047 docs(example): replace useQuery to getQuery
  docs/content/2.guide/2.directory-structure/1.server.md
  examples/app/error-handling/server/middleware/error.ts
  examples/composables/use-fetch/server/api/[...hello].ts
  examples/experimental/wasm/server/api/sum.ts
Labels: documentation

#7940 fix(nuxt): page hydration and double load
  packages/nuxt/src/app/components/layout.ts
  packages/nuxt/src/app/components/nuxt-root.vue
  packages/nuxt/src/app/entry.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/pages/runtime/page.ts
  test/basic.test.ts
  test/fixtures/basic/layouts/custom-async.vue
  test/fixtures/basic/layouts/custom2.vue
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/async-parent.vue
  test/fixtures/basic/pages/async-parent/child.vue
  test/fixtures/basic/pages/fixed-keyed-child-parent.vue
  test/fixtures/basic/pages/fixed-keyed-child-parent/[foo].vue
  test/fixtures/basic/pages/internal-layout.vue
  test/fixtures/basic/pages/keyed-child-parent.vue
  test/fixtures/basic/pages/keyed-child-parent/[foo].vue
  test/fixtures/basic/pages/with-layout.vue
  test/fixtures/basic/pages/with-layout2.vue
  test/utils.ts
Labels: bug

#8064 fix(schema): declare `untyped` dependency
  packages/schema/package.json
Labels: bug, schema, 🔨 p3-minor-bug

#7984 fix(nuxt): use correct cache and add baseURL to payload
  packages/nuxt/src/app/composables/payload.ts
Labels: bug, 🔨 p3-minor-bug

#7128 feat(nuxt): add default slot to `<NuxtLoadingIndicator>`
  docs/content/3.api/2.components/4.nuxt-loading-indicator.md
  packages/nuxt/src/app/components/nuxt-loading-indicator.ts
Labels: enhancement, 🍰 p2-nice-to-have

#7870 feat(pages): add `validate` hook for `definePageMeta`
  docs/content/1.getting-started/5.routing.md
  docs/content/3.api/3.utils/define-page-meta.md
  docs/content/7.migration/7.component-options.md
  packages/nuxt/src/app/plugins/router.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/runtime/composables.ts
  packages/nuxt/src/pages/runtime/router.ts
  packages/nuxt/src/pages/runtime/validate.ts
  test/basic.test.ts
  test/fixtures/basic/pages/[...slug].vue
Labels: enhancement, 🍰 p2-nice-to-have

#7864 feat(nuxt): refresh override for data fetching composables
  docs/content/1.getting-started/6.data-fetching.md
  docs/content/3.api/1.composables/use-async-data.md
  docs/content/3.api/1.composables/use-fetch.md
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/fetch.ts
  test/basic.test.ts
  test/fixtures/basic/pages/useAsyncData/override.vue
Labels: enhancement, 🍰 p2-nice-to-have

#7868 feat(schema, nuxt): allow user-configurable `serverDir`
  packages/nuxt/src/core/nitro.ts
  packages/schema/src/config/_common.ts
Labels: enhancement, 🍰 p2-nice-to-have

#7893 perf(nitro): respond with early hints in node-based environments
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: enhancement, nitro, 🍰 p2-nice-to-have, performance

#7527 feat(nuxt): parse html to treeshake client-only components
  packages/nuxt/package.json
  packages/nuxt/src/components/tree-shake.ts
  yarn.lock
Labels: bug, enhancement, 🔨 p3-minor-bug

#7989 fix(vite): prevent overlap between vite assets and app routes
  packages/vite/src/client.ts
Labels: bug, vite, 🔨 p3-minor-bug

#7412 feat(nuxt): wrap `#components` client exports with createClientOnly
  docs/content/2.guide/2.directory-structure/1.components.md
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/templates.ts
  test/basic.test.ts
  test/fixtures/basic/components/BreaksServer.client.ts
  test/fixtures/basic/pages/client-only-explicit-import.vue
  test/fixtures/basic/pages/client.vue
Labels: bug, 🔨 p3-minor-bug

#7938 feat(nuxt): add `ssr` route rule to enable SPA mode
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  test/basic.test.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/route-rules/spa.vue
Labels: enhancement, nitro, 🍰 p2-nice-to-have

#8136 docs: fix 404 page
  docs/package.json
  docs/yarn.lock
Labels: documentation

#8151 docs: use `RouterConfig` interface in examples
  docs/content/2.guide/2.directory-structure/1.pages.md
Labels: documentation

#8160 chore: bump example dependencies
  examples/advanced/config-extends/package.json
  examples/advanced/jsx/package.json
  examples/advanced/module-extend-pages/package.json
  examples/advanced/testing/package.json
  examples/app-config/package.json
  examples/app/error-handling/package.json
  examples/app/plugins/package.json
  examples/app/teleport/package.json
  examples/auto-imports/components/package.json
  examples/auto-imports/composables/package.json
  examples/composables/use-async-data/package.json
  examples/composables/use-async-data/server/api/hello.ts
  examples/composables/use-async-data/server/api/hello/[slug].ts
  examples/composables/use-cookie/package.json
  examples/composables/use-fetch/package.json
  examples/composables/use-head/package.json
  examples/composables/use-state/package.json
  examples/essentials/hello-world/package.json
  examples/experimental/reactivity-transform/package.json
  examples/experimental/vite-node/package.json
  examples/experimental/wasm/package.json
  examples/other/locale/package.json
  examples/routing/layouts/package.json
  examples/routing/middleware/package.json
  examples/routing/nuxt-link/package.json
  examples/routing/pages/package.json
  examples/routing/universal-router/package.json
  examples/server/routes/package.json
  yarn.lock
Labels: documentation, chore

#8188 perf(nuxt): remove `vue-router` dependency from minimal app
  packages/nuxt/src/app/components/nuxt-link.ts
  packages/nuxt/src/app/composables/component.ts
  packages/nuxt/src/pages/runtime/page.ts
  packages/nuxt/src/pages/runtime/utils.ts
Labels: bug, 🔨 p3-minor-bug, performance

#7690 feat(nuxt): add hook debug mode
  packages/nuxt/package.json
  packages/nuxt/src/app/plugins/debug.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/schema/src/config/_common.ts
  yarn.lock
Labels: enhancement, 🍰 p2-nice-to-have

#8190 feat(nuxt)!: `refresh` to override previous requests by default
  docs/content/1.getting-started/6.data-fetching.md
  docs/content/3.api/1.composables/use-async-data.md
  docs/content/3.api/1.composables/use-fetch.md
  packages/nuxt/src/app/composables/asyncData.ts
  test/fixtures/basic/pages/useAsyncData/override.vue
Labels: enhancement

#8197 refactor(nuxt): deprecate `<Script>` component tag in template
  packages/nuxt/src/head/runtime/components.ts
Labels: enhancement, 🍰 p2-nice-to-have

#8226 fix(webpack): add global to new line
  packages/webpack/src/plugins/dynamic-base.ts
Labels: bug, webpack, 🔨 p3-minor-bug

#7895 chore: use pnpm for framework monorepo
  .github/workflows/ci.yml
  .github/workflows/docs-e2e.yml
  .github/workflows/docs.yml
  .gitignore
  .gitpod.yml
  .npmrc
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarn/plugins/@yarnpkg/plugin-typescript.cjs
  .yarn/releases/yarn-3.2.4.cjs
  .yarnrc.yml
  README.md
  docs/.gitignore
  docs/.yarnrc.yml
  docs/content/5.community/4.framework-contribution.md
  docs/nuxt.config.ts
  docs/package.json
  docs/scripts/make-schema.sh
  docs/yarn.lock
  lerna.json
  package.json
  playground/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  scripts/_utils.ts
  scripts/bump-edge.ts
  scripts/bump-rc.sh
  scripts/bump-rc.ts
  scripts/example.sh
  scripts/release-edge.sh
  scripts/release-rc.sh
  test/fixtures/basic/package.json
  yarn.lock
Labels: chore, 🧹 p1-chore

#8225 perf(nuxt): improve link prefetching
  packages/nuxt/src/app/components/nuxt-link.ts
  packages/nuxt/src/app/composables/index.ts
  packages/nuxt/src/app/composables/preload.ts
  packages/nuxt/src/app/plugins/cross-origin-prefetch.client.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/imports/presets.ts
  packages/schema/src/config/experimental.ts
Labels: enhancement, 🍰 p2-nice-to-have, performance

#7954 feat(schema): add experimental `routesRules`
  packages/schema/package.json
  packages/schema/src/config/nitro.ts
  pnpm-lock.yaml
Labels: nitro, schema, 🍰 p2-nice-to-have

#8251 refactor: use `getRouteRules`
  packages/nuxt/package.json
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/schema/package.json
  pnpm-lock.yaml
Labels: bug

#8255 fix(nuxt): avoid preloading external routes
  packages/nuxt/src/app/components/nuxt-link.ts
Labels: bug, 🔨 p3-minor-bug

#8264 feat(nuxt): allow disabling early hints
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/schema/src/config/experimental.ts
Labels: enhancement

#8278 fix(nuxt): lazy-load entry CSS
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/nuxt/src/core/templates.ts
  packages/vite/src/server.ts
  test/basic.test.ts
  test/fixtures/basic/extends/node_modules/foo/server/api/foo.ts
  test/fixtures/basic/extends/node_modules/foo/server/middleware/foo.ts
Labels: bug, 🔨 p3-minor-bug

#8299 fix(nuxt): don't use or assignment
  packages/nuxt/src/app/composables/preload.ts
Labels: bug

#3851 feat(nuxt): default router scroll behavior
  docs/content/3.api/4.advanced/1.hooks.md
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/runtime/composables.ts
  packages/nuxt/src/pages/runtime/page.ts
  packages/nuxt/src/pages/runtime/router.options.ts
Labels: enhancement, nuxt3, 🍰 p2-nice-to-have

#8324 build(pkg): support node 19
  package.json
  packages/kit/package.json
  packages/nuxi/package.json
  packages/nuxt/package.json
  packages/schema/package.json
  packages/test-utils/package.json
  packages/vite/package.json
  packages/webpack/package.json
Labels: chore

#8325 refactor(test-utils)!: update vitest args
  packages/test-utils/src/run.ts
Labels: refactor, test-utils

#8326 chore(nuxt): add type for headers
  packages/nuxt/src/core/runtime/nitro/error.ts
Labels: chore

#8374 feat(nuxt): make `useFetch` options reactive
  docs/content/3.api/1.composables/use-fetch.md
  packages/nuxt/src/app/composables/fetch.ts
Labels: enhancement, 🍰 p2-nice-to-have

#8370 fix(nuxt): don't load payloads for external urls
  packages/nuxt/src/app/plugins/payload.client.ts
Labels: bug, 🔨 p3-minor-bug

#8385 docs: add missing `app` key for transitions
  docs/content/1.getting-started/5.transitions.md
Labels: documentation

#8389 fix(vite): invalidate virtual modules with `vite-node`
  packages/vite/src/vite-node.ts
Labels: bug, vite, 🔨 p3-minor-bug

#8434 docs: disable transitions by default
  docs/nuxt.config.ts
Labels: documentation

#8421 fix(nuxt): avoid directly importing `vue-router` inside `<NuxtLayout>`
  packages/nuxt/src/app/components/layout.ts
  packages/nuxt/src/pages/module.ts
Labels: bug, pages, 🔨 p3-minor-bug

#8413 feat(kit): add `updateTemplates` utility
  docs/content/3.api/4.advanced/2.kit.md
  packages/kit/src/template.ts
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/imports/module.ts
  packages/nuxt/src/pages/module.ts
  packages/schema/src/types/hooks.ts
Labels: enhancement, kit, 🍰 p2-nice-to-have, performance

#8453 fix(kit): use `pathe` to resolve aliases
  packages/kit/src/resolve.ts
Labels: bug, kit, 🔨 p3-minor-bug

#8457 chore(examples): add missing dependency and script for testing example
  examples/advanced/testing/package.json
  pnpm-lock.yaml
Labels: documentation, chore

#8458 fix(test-utils): override `NITRO_PORT` as well
  packages/test-utils/src/server.ts
Labels: bug, 🔨 p3-minor-bug, test-utils

#8464 feat(nuxt): add dev warnings when `setPageLayout` is used incorrectly
  packages/nuxt/src/app/composables/router.ts
Labels: enhancement, dx

#8469 fix(nuxt): allow responding with custom headers from `error.vue`
  packages/nuxt/src/core/runtime/nitro/error.ts
Labels: bug, 🍰 p2-nice-to-have

#8486 fix(schema): disable early hints by default
  packages/schema/src/config/experimental.ts
Labels: schema

#7950 feat: add dev-only component
  docs/content/2.guide/2.directory-structure/1.components.md
  packages/nuxt/src/app/components/dev-only.mjs
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/dev-only.ts
Labels: enhancement, 🍰 p2-nice-to-have

#8504 fix(kit): don't require nuxt when resolving path
  packages/kit/src/resolve.ts
Labels: bug, kit

#8506 chore: reenable auto-upgrades for vueuse/head
  renovate.json
Labels: chore

#8535 docs: generate docs for unversioned schema
  docs/scripts/gen-docs.ts
Labels: documentation
