Repository nuxt/framework, pull requests merged in 2022-09, with the labels that each got.

#7124 docs: add explanatory comment before universal router stubs
  packages/nuxt/src/app/plugins/router.ts
Labels: documentation

#7130 refactor(nuxt): remove unused `meta:register` hook
  docs/content/3.api/4.advanced/1.hooks.md
  packages/nuxt/src/app/nuxt.ts
Labels: bug, 🍰 p2-nice-to-have

#7158 fix: improve `autoImports` deprecation dx
  packages/kit/src/auto-import.ts
  packages/kit/src/imports.ts
  packages/kit/src/index.ts
  packages/nuxt/package.json
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/imports/module.ts
  yarn.lock
Labels: enhancement

#7044 docs: add note about `useFetch` auto generated key
  docs/content/3.api/1.composables/use-fetch.md
Labels: documentation

#7072 docs(api): enhance `useHead` composable
  docs/content/3.api/1.composables/use-head.md
Labels: documentation

#7120 docs: add note about fetching data on initial load
  docs/content/3.api/1.composables/use-async-data.md
  docs/content/3.api/1.composables/use-fetch.md
Labels: documentation

#7160 feat(nuxt, vite): inline global and component styles in server response
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/schema/src/config/experimental.ts
  packages/vite/src/plugins/ssr-styles.ts
  packages/vite/src/server.ts
  test/basic.test.ts
  test/fixtures/basic/assets/assets.css
  test/fixtures/basic/assets/functional.css
  test/fixtures/basic/assets/global.css
  test/fixtures/basic/assets/plugin.css
  test/fixtures/basic/components/ClientOnlyScript.client.vue
  test/fixtures/basic/components/FunctionalComponent.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/styles.vue
  test/fixtures/basic/plugins/style.ts
Labels: enhancement, 🍰 p2-nice-to-have, performance

#7084 docs(guide): add .client and .server components documentation
  docs/content/2.guide/3.directory-structure/4.components.md
Labels: documentation

#7129 feat(nuxt): custom `history` and `routes` for `app/router.options.ts`
  docs/content/2.guide/3.directory-structure/10.pages.md
  packages/nuxt/src/pages/runtime/router.ts
  packages/schema/src/types/router.ts
Labels: enhancement, 🍰 p2-nice-to-have

#7231 docs: fix markdown file name
  docs/content/3.api/2.components/6.nuxt-welcome.md
Labels: documentation

#7232 docs(api): navigate to first item in list
  docs/content/3.api/index.md
Labels: documentation

#7180 docs(api): add example for fetch interceptors
  docs/content/3.api/1.composables/use-fetch.md
Labels: documentation

#7234 fix(vite): use baseURL + assetsDir as base in dev mode
  packages/vite/src/client.ts
Labels: bug, vite, 🍰 p2-nice-to-have

#7089 docs(deploy): add node cluster mode
  docs/content/2.guide/5.deploy/1.node-server.md
Labels: documentation

#7248 feat(nuxt): support experimental flag to render no client-side js
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/schema/src/config/experimental.ts
Labels: enhancement, 🍰 p2-nice-to-have

#7260 fix(vite): pass ssr condition to `getModuleByUrl`
  packages/vite/src/utils/warmup.ts
Labels: bug, vite, 🍰 p2-nice-to-have

#7268 refactor(vite): reuse resolved server entry from context
  packages/vite/src/server.ts
  packages/vite/src/vite-node.ts
Labels: vite, 🍰 p2-nice-to-have

#7271 fix(nuxi): pass value of `https` through to vite-node
  docs/content/3.api/5.commands/dev.md
  packages/nuxi/src/commands/dev.ts
Labels: bug, vite, 🔨 p3-minor-bug

#7270 feat(kit): add `addImportsSources` utility
  packages/kit/src/imports.ts
  packages/nuxt/src/core/nuxt.ts
Labels: enhancement, 🍰 p2-nice-to-have

#7290 fix(nuxt): don't override payload error if it is present
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  test/basic.test.ts
  test/fixtures/basic/pages/error.vue
Labels: bug, 🔨 p3-minor-bug

#7288 fix(nuxt): don't try to set cookie after redirect
  packages/nuxt/src/app/composables/cookie.ts
Labels: bug, 🔨 p3-minor-bug

#7275 fix(webpack): promisify webpack dev/hot handlers using `h3.promisifyHandler`
  packages/schema/build.config.ts
  packages/schema/src/types/hooks.ts
  packages/webpack/build.config.ts
  packages/webpack/src/configs/client.ts
  packages/webpack/src/webpack.ts
Labels: bug, webpack, ❗ p4-important

#7264 perf(vite): remove duplicate css links from rendered page when inlined
  packages/vite/src/client.ts
  packages/vite/src/plugins/ssr-styles.ts
  packages/vite/src/server.ts
  test/basic.test.ts
  test/fixtures/basic/components/ClientOnlyScript.client.vue
  test/fixtures/basic/nuxt.config.ts
Labels: enhancement, 🍰 p2-nice-to-have

#7312 test: use semantic `runIf` and `skipIf` helpers
  test/basic.test.ts
Labels: test, 🧹 p1-chore

#5227 feat(nuxt): add `clearNuxtData`
  docs/content/2.guide/2.features/5.data-fetching.md
  docs/content/3.api/3.utils/clear-nuxt-data.md
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/nuxt.ts
Labels: enhancement

#7313 feat(vite, webpack): allow client-side sourcemaps in production
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/imports/module.ts
  packages/nuxt/src/pages/module.ts
  packages/schema/src/config/build.ts
  packages/schema/src/types/config.ts
  packages/vite/src/client.ts
  packages/vite/src/server.ts
  packages/vite/src/vite.ts
  packages/webpack/src/configs/client.ts
  packages/webpack/src/configs/server.ts
  packages/webpack/src/webpack.ts
Labels: bug, nitro, vite, webpack, 🍰 p2-nice-to-have

#7327 fix(schema): mark vite server as optional
  packages/schema/src/types/config.ts
Labels: bug, schema

#7335 fix(nuxt): allow `abortMiddleware` to receive a nuxt error or error options
  packages/nuxt/src/app/composables/router.ts
  test/basic.test.ts
  test/fixtures/basic/middleware/abort.global.ts
Labels: enhancement, 🍰 p2-nice-to-have

#7333 fix(webpack): don't parse styles for composable keys
  packages/vite/src/plugins/composable-keys.ts
  test/fixtures/basic/pages/keyed-composables.vue
Labels: bug, webpack, ❗ p4-important

#7342 fix(vite): allow overriding vite sourcemap
  packages/vite/src/client.ts
  packages/vite/src/server.ts
Labels: bug, vite, 🔨 p3-minor-bug

#7359 fix(schema): resolve `ssr`
  packages/schema/src/config/_common.ts
Labels: bug, vite, ❗ p4-important

#7358 fix(kit): add default config layer without `nuxt.config` file
  packages/kit/src/loader/config.ts
Labels: bug, ❗ p4-important

#7347 fix(vite): update render if it is invalidated
  packages/vite/src/runtime/vite-node.mjs
Labels: bug, dx, 🔨 p3-minor-bug

#7364 docs(head): enhance usehead and fix broken links
  docs/content/2.guide/2.features/4.head-management.md
  docs/content/4.examples/3.composables/use-head.md
  docs/content/migration/4.meta.md
Labels: documentation

#7377 fix(vite): warmup improvements
  packages/vite/src/client.ts
  packages/vite/src/runtime/vite-node.mjs
  packages/vite/src/server.ts
  packages/vite/src/utils/warmup.ts
  packages/vite/src/vite.ts
Labels: bug, vite, 🍰 p2-nice-to-have

#7378 fix(nuxi): don't include an array of paths within an array
  packages/nuxi/src/utils/cjs.ts
Labels: bug, cli

#7380 fix(vite): write dev manifest before spa build
  packages/vite/src/server.ts
Labels: bug, vite, ❗ p4-important

#7389 fix(nuxt): de-default layout/component imports
  packages/nuxt/src/app/components/nuxt-error-page.vue
  packages/nuxt/src/app/components/nuxt-root.vue
  packages/nuxt/src/components/loader.ts
  packages/nuxt/src/core/templates.ts
Labels: bug, ❗ p4-important

#7386 fix(nuxt): always inline entry styles
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/vite/src/plugins/ssr-styles.ts
Labels: bug, 🔨 p3-minor-bug

#7344 fix(nuxt): do not apply import protection to top-level resolution
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/import-protection.ts
Labels: bug, 🍰 p2-nice-to-have

#7435 fix(nuxt): use more specific `FetchError` for `useFetch` errors
  packages/nuxt/src/app/composables/fetch.ts
  test/fixtures/basic/types.ts
Labels: bug, types, 🍰 p2-nice-to-have

#7416 test(nuxt): add tests for import protection plugin
  packages/nuxt/src/core/plugins/import-protection.ts
  packages/nuxt/test/import-protection.test.ts
Labels: test

#7436 fix(vite): use same asset filenames between server and client
  packages/vite/src/client.ts
  packages/vite/src/vite.ts
Labels: bug, vite, 🔨 p3-minor-bug

#7442 feat(nuxt): allow exposing type augmentations from extends layers
  packages/nuxt/src/core/nuxt.ts
  test/fixtures/basic/extends/bar/index.d.ts
  test/fixtures/basic/types.ts
Labels: enhancement, 🍰 p2-nice-to-have

#7440 fix(vite): don't fail builds for virtual modules that don't support inlining
  packages/vite/src/plugins/ssr-styles.ts
  test/fixtures/basic/nuxt.config.ts
Labels: bug, vite, ❗ p4-important

#7439 feat(nuxt): add `workspaceDir` option and add it to `modulesDir`
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/schema/build.config.ts
  packages/schema/package.json
  packages/schema/src/config/_common.ts
  yarn.lock
Labels: enhancement, 🍰 p2-nice-to-have

#7460 perf(nuxt): only inject preload helper when webpack is used
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/templates.ts
  packages/schema/src/config/build.ts
  packages/schema/src/types/config.ts
Labels: bug, enhancement, 🍰 p2-nice-to-have, performance

#7473 ci: crawl docs site for new deployments to track broken links
  .github/workflows/docs-e2e.yml
  package.json
  scripts/crawl.mjs
  yarn.lock
Labels: documentation, chore, 🧹 p1-chore

#4329 feat(nuxt): support prefetching `<nuxt-link>`
  docs/content/3.api/2.components/4.nuxt-link.md
  docs/content/3.api/4.advanced/1.hooks.md
  packages/nuxt/src/app/components/nuxt-link.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/app/plugins/payload.client.ts
  test/basic.test.ts
  test/fixtures/basic/pages/random/[id].vue
Labels: enhancement, app

#7486 fix(nuxt): only delete assets when building
  packages/nuxt/src/core/nuxt.ts
Labels: bug, 🔥 p5-urgent

#7487 refactor(nuxt): use relative imports into composables
  packages/nuxt/src/app/components/nuxt-link.ts
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/cookie.ts
  packages/nuxt/src/app/composables/error.ts
  packages/nuxt/src/app/composables/hydrate.ts
  packages/nuxt/src/app/composables/payload.ts
  packages/nuxt/src/app/composables/preload.ts
  packages/nuxt/src/app/composables/router.ts
  packages/nuxt/src/app/composables/ssr.ts
  packages/nuxt/src/app/composables/state.ts
  packages/nuxt/test/nuxt-link.test.ts
Labels: chore, 🍰 p2-nice-to-have

#7492 feat(nuxt): allow passing transition & keepalive props to <NuxtPage>
  packages/nuxt/src/pages/runtime/page.ts
Labels: enhancement, 🍰 p2-nice-to-have

#7495 docs(getting-started): add routing page
  docs/content/1.getting-started/5.routing.md
  docs/content/1.getting-started/index.md
Labels: documentation

#7522 fix(nuxt): do not pass prefetched class to custom link
  packages/nuxt/src/app/components/nuxt-link.ts
Labels: bug, 🔨 p3-minor-bug

#7540 docs: add note about link prefetching
  docs/content/1.getting-started/5.routing.md
Labels: documentation

#7541 fix(schema): update resolver for `cssSourceMap` to new `sourcemap`
  packages/schema/src/config/build.ts
Labels: bug, bridge, types, 🍰 p2-nice-to-have

#7494 fix(nuxt): pass fully resolved path to nitro dist files
  packages/nuxt/src/core/nitro.ts
  packages/vite/src/server.ts
Labels: bug, 🔨 p3-minor-bug

#7577 fix(nuxi): print resolved public directory after generate
  packages/nuxi/src/commands/build.ts
  packages/nuxi/src/commands/generate.ts
Labels: bug, cli, 🔨 p3-minor-bug

#7574 fix(nuxt): load payload after middleware and once final route is resolved
  packages/nuxt/src/app/plugins/payload.client.ts
Labels: bug, 🔨 p3-minor-bug

#7567 fix(nuxt): keep `state` in initial state instead of extracting it
  packages/nuxt/src/app/plugins/payload.client.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  test/basic.test.ts
Labels: ❗ p4-important

#7593 fix(nuxi): backward compatibility for kit <= RC.10 without `useNitro`
  packages/nuxi/src/commands/build.ts
Labels: bug, cli, ❗ p4-important

#7639 docs: fix typo in nitro options in wasm example
  examples/experimental/wasm/nuxt.config.ts
Labels: documentation

#7622 fix(vite, webpack): avoid generating keys where a key is already provided
  packages/vite/src/plugins/composable-keys.ts
Labels: bug, vite, webpack, ❗ p4-important, performance

#7659 fix(nuxt): don't treeshake client-only fallback templates
  packages/nuxt/src/components/tree-shake.ts
  test/basic.test.ts
  test/fixtures/basic/pages/client-only-components.vue
Labels: bug, 🔨 p3-minor-bug

#7673 fix(nuxt): strip non-`.vue` extensions from component types
  packages/nuxt/src/components/templates.ts
Labels: bug, types, 🔨 p3-minor-bug

#7618 docs(api): add `defineNuxtComponent` utils
  docs/content/1.getting-started/6.data-fetching.md
  docs/content/3.api/3.utils/define-nuxt-component.md
  docs/utils/createTitle.js
Labels: documentation

#7643 docs(testing): move modules testing section to module authors guide
  docs/content/1.getting-started/9.testing.md
  docs/content/2.guide/4.going-further/3.modules.md
Labels: documentation

#7679 fix(nuxt): only observe tag elements for `<NuxtLink>` prefetching
  packages/nuxt/src/app/components/nuxt-link.ts
Labels: bug, 🔨 p3-minor-bug

#7556 docs(getting-started): add views page
  docs/.gitignore
  docs/content/1.getting-started/3.views.md
  docs/static/img/getting-started/views/app.svg
  docs/static/img/getting-started/views/components.svg
  docs/static/img/getting-started/views/layouts.svg
  docs/static/img/getting-started/views/pages.svg
Labels: documentation

#7710 fix(nuxt): export and auto-import `clearNuxtData`
  packages/nuxt/src/app/composables/index.ts
  packages/nuxt/src/imports/presets.ts
  packages/nuxt/test/auto-imports.test.ts
Labels: bug, 🔨 p3-minor-bug

#7712 fix(test-utils): support vitest v0.20.x
  packages/test-utils/src/run.ts
Labels: bug, cli, 🔨 p3-minor-bug, test-utils

#7689 docs(getting-started): configuration page
  docs/content/1.getting-started/3.configuration.md
Labels: documentation

#7717 docs: recommend to not overwrite some keys in tsconfig
  docs/content/2.guide/2.directory-structure/3.tsconfig.md
Labels: documentation

#7734 docs(navigate-to): use await instead of return
  docs/content/3.api/3.utils/navigate-to.md
Labels: documentation

#7726 fix(nuxi): include `workspaceDir` in tsconfig include
  packages/nuxi/src/utils/prepare.ts
  test/fixtures/basic/nuxt.config.ts
Labels: bug, enhancement, cli, 🍰 p2-nice-to-have

#7728 fix(nuxi): stub `defineNuxtConfig` for `nuxi info`
  packages/nuxi/src/commands/info.ts
Labels: bug, cli, 🔨 p3-minor-bug

#7746 feat(nuxt): support `redirect` within page metadata
  packages/nuxt/src/pages/runtime/composables.ts
  packages/nuxt/src/pages/utils.ts
  packages/schema/src/types/hooks.ts
  test/basic.test.ts
  test/fixtures/basic/pages/index.vue
  test/fixtures/basic/pages/redirect.vue
Labels: enhancement, 🍰 p2-nice-to-have

#7748 fix(nuxt): do not warn for non-existent default layout
  packages/nuxt/src/app/components/layout.ts
Labels: bug, dx, 🍰 p2-nice-to-have

#7720 fix(nuxt): respect immediate option in `useFetch`
  packages/nuxt/src/app/composables/fetch.ts
Labels: bug, 🔨 p3-minor-bug

#7809 fix(nuxt): respect `baseURL` when rendering payload path
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: bug, 🔨 p3-minor-bug

#7782 docs: document nitro hooks
  docs/content/2.guide/4.going-further/2.hooks.md
  docs/content/3.api/4.advanced/1.hooks.md
Labels: documentation

#7781 docs(roadmap): remove not working link from `nuxt/auth`
  docs/content/5.community/5.roadmap.md
Labels: documentation

#7775 docs: updated nuxt bridge migration guide
  docs/content/bridge/1.overview.md
Labels: documentation

#7745 fix(nuxt): don't disable scripts in dev mode with experimental `noScripts`
  packages/nuxt/src/core/nitro.ts
Labels: bug, 🔨 p3-minor-bug

#7765 docs: merge deployment pages in getting started
  docs/content/1.getting-started/10.deployment.md
  docs/content/2.guide/3.deploy/1.node-server.md
  docs/content/2.guide/3.deploy/2.static-hosting.md
  docs/content/2.guide/3.deploy/3.presets.md
  docs/content/2.guide/3.deploy/index.md
  docs/content/2.guide/3.deploy/providers/aws.md
  docs/content/2.guide/3.deploy/providers/azure.md
  docs/content/2.guide/3.deploy/providers/cloudflare.md
  docs/content/2.guide/3.deploy/providers/digitalocean.md
  docs/content/2.guide/3.deploy/providers/firebase.md
  docs/content/2.guide/3.deploy/providers/heroku.md
  docs/content/2.guide/3.deploy/providers/index.md
  docs/content/2.guide/3.deploy/providers/layer0.md
  docs/content/2.guide/3.deploy/providers/netlify.md
  docs/content/2.guide/3.deploy/providers/render.md
  docs/content/2.guide/3.deploy/providers/stormkit.md
  docs/content/2.guide/3.deploy/providers/vercel.md
  docs/static/_redirects
Labels: documentation

#7810 docs: add newline at end of sass import
  docs/content/1.getting-started/4.assets.md
Labels: documentation
