Repository nuxt/framework, pull requests merged in 2023-02, with the labels that each got.

#8912 docs: add `useError` composable
  docs/3.api/1.composables/use-error.md
Labels: documentation, 3.x

#8953 docs: clarify augmenting input/output app config
  docs/2.guide/2.directory-structure/3.app-config.md
Labels: documentation, 3.x

#8116 docs: add explanation of composable lifecycle
  docs/2.guide/1.concepts/1.auto-imports.md
Labels: documentation, 3.x

#8789 fix(nuxt): treeshake client-only components with placeholders
  packages/nuxt/src/components/tree-shake.ts
Labels: bug, 🔨 p3-minor-bug, 3.x

#9952 fix(nuxt): don't exclude pnpm layers from nitro esbuild/imports
  packages/nuxt/src/core/nitro.ts
Labels: bug, 3.x

#8713 fix(nuxt): use parser to treeshake `<ClientOnly>`
  packages/nuxt/package.json
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/tree-shake.ts
  packages/nuxt/test/__snapshots__/treeshake-client.test.ts.snap
  packages/nuxt/test/fixture/components/client/WithClientOnlySetup.vue
  packages/nuxt/test/scan-components.test.ts
  packages/nuxt/test/treeshake-client.test.ts
  packages/nuxt/test/utils.ts
  pnpm-lock.yaml
  test/basic.test.ts
  test/fixtures/basic/pages/client-only-components.vue
  test/fixtures/basic/pages/client.vue
  vitest.config.ts
Labels: bug, ❗ p4-important, 3.x
