Repository nuxt/framework, pull requests merged in 2023-01, with the labels that each got.

#10002 docs: remove nuxt 2 information from `generate` schema
  packages/schema/src/config/generate.ts
Labels: documentation

#10046 fix(nuxt): include components `runtime` dir in build output
  packages/nuxt/build.config.ts
  packages/nuxt/src/components/loader.ts
Labels: bug, ❗ p4-important

#10063 chore(docs): revert lockfile
  docs/yarn.lock
Labels: chore

#10085 chore: case police update
  docs/content/4.support/1.solutions.md
  docs/content/4.support/2.agencies/2.ship-shape.md
  docs/content/4.support/2.agencies/3.64robots.md
  docs/content/4.support/2.agencies/4.passionate-people.md
  docs/content/4.support/2.agencies/5.curotec.md
  docs/content/4.support/2.agencies/6.mirahi.md
  docs/content/4.support/2.agencies/7.webreinvent.md
  docs/content/4.support/2.agencies/8.software-things.md
  docs/content/4.support/2.agencies/9.zen-architects.md
  docs/content/4.support/2.agencies/91.funkhaus.md
  docs/content/4.support/2.agencies/92.the-coding-machine.md
  docs/content/4.support/2.agencies/93.epicmax.md
  docs/content/4.support/2.agencies/94.brain.md
  docs/content/4.support/2.agencies/96.macopedia.md
  docs/content/v3.md
  packages/kit/src/build.ts
  packages/nuxt/src/app/config.ts
  packages/nuxt/src/components/loader.ts
  packages/nuxt/src/pages/page-meta.ts
  packages/schema/src/config/app.ts
  packages/schema/src/types/components.ts
  packages/schema/src/types/hooks.ts
  packages/webpack/src/configs/client.ts
  packages/webpack/src/presets/style.ts
  test/basic.test.ts
Labels: chore

#10094 fix(nuxt): add `build.transpile` strings to nitro inline list
  packages/nuxt/src/core/nitro.ts
Labels: bug, 🔨 p3-minor-bug

#10017 fix(nuxt): allow overriding lower layer composables
  packages/nuxt/src/imports/module.ts
  test/basic.test.ts
  test/fixtures/basic/composables/override-base.ts
  test/fixtures/basic/extends/bar/composables/base.ts
  test/fixtures/basic/pages/extends.vue
Labels: bug, 🍰 p2-nice-to-have

#9627 fix(nuxt): avoid injecting url helpers into `globalThis`
  packages/nuxt/src/core/nitro.ts
  packages/vite/src/server.ts
Labels: bug, 🔨 p3-minor-bug

#10011 fix(nuxt): name anonymous components in render tree
  packages/nuxt/src/app/components/layout.ts
  packages/nuxt/src/app/components/utils.ts
  packages/nuxt/src/pages/runtime/page.ts
Labels: bug, enhancement, 🍰 p2-nice-to-have

#10076 docs: add port example in `ecosystem.config`
  docs/content/1.docs/1.getting-started/10.deployment.md
Labels: documentation

#10059 docs: add description of returning different status codes
  docs/content/1.docs/2.guide/2.directory-structure/1.server.md
Labels: documentation

#10113 feat(nuxt): support server components with extracted payloads
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/components/runtime/server-component.ts
  packages/nuxt/src/core/nuxt.ts
  test/basic.test.ts
  test/fixtures/basic/pages/random/[id].vue
  test/fixtures/basic/types.ts
Labels: enhancement, 🍰 p2-nice-to-have, 3.x

#10139 docs: add buttons slot on PageHero component
  docs/content/3.showcase.md
  docs/content/4.support/2.agencies/1.index.md
  docs/content/4.support/3.us.md
  docs/content/4.support/4.jobs.md
  docs/content/design-kit.md
  docs/public/assets/design-kit/nuxt-assets.zip
Labels: documentation, 3.x

#9900 docs: rename layer0 to Edgio
  docs/content/1.docs/1.getting-started/10.deployment.md
Labels: documentation, 3.x

#9962 fix(nuxi): prevent showing stack traces while scaffolding
  packages/nuxi/src/commands/init.ts
Labels: bug, 3.x

#9771 feat(kit): add `extendRouteRules` method
  docs/content/1.docs/3.api/4.advanced/2.kit.md
  packages/kit/src/pages.ts
Labels: enhancement, kit, 🍰 p2-nice-to-have, 3.x
